### ISSUE TITLE
Adding to bioconda

### ISSUE THREAD

**Issue by TomHarrop** [mossmatters/HybPiper#116]
Hi,

I'd like a version-tagged Docker container for hybpiper. I modified the [hybpiper recipe from anaconda](https://anaconda.org/chrisjackson-pellicle/hybpiper) to submit to bioconda in this PR: https://github.com/bioconda/bioconda-recipes/pull/40526

Let me know if there are any issues.

**Comment by nbat64** [comment]
Hello,
I tried to install it with mamba and get this error:
The following package could not be installed
└─ hybpiper   is uninstallable because it requires
   └─ bbmap >=38.44 , which does not exist (perhaps a missing channel).

**Comment by chrisjackson-pellicle** [comment]
Hi @TomHarrop,

Thanks very much for doing that - it's been on our to-do list for a while, but kept slipping...

I see that the Bioconda PR is now merged, and that your `meta.yaml` specified HybPiper version 2.1.1 (the latest release at the time of your PR). I've recently made a release for HybPiper version 2.1.3, which has a couple of important updates and bugfixes compared to 2.1.1 (see the [changelog](https://github.com/mossmatters/HybPiper/blob/master/change_log.md)). 

Are you able to update the Bioconda recipe to 2.1.3? I'll do this myself for future releases, but I figure if you've got it all set up anyway...:)

Cheers,

Chris

**Comment by TomHarrop** [comment]
It [autoupdated](https://github.com/bioconda/bioconda-recipes/pull/40554) without me doing anything :100: 

I'm not sure why the container hasn't shown up, I'll follow up with bioconda.

**Comment by TomHarrop** [comment]
The containers are at https://quay.io/repository/biocontainers/hybpiper?tab=tags. You can close this issue when you're ready.

**Comment by nylander** [comment]
> Hello, I tried to install it with mamba and get this error: The following package could not be installed └─ hybpiper is uninstallable because it requires └─ bbmap >=38.44 , which does not exist (perhaps a missing channel).

@nbat64 :

Try
```
$ mamba create -n hybpiper -c chrisjackson-pellicle hybpiper -c bioconda
```
