### ISSUE TITLE
Issues installing hybpiper

### ISSUE THREAD

**Issue by veronicamb** [mossmatters/HybPiper#118]
I'm trying to install hybpiper but I keep getting the same "package not found" message.

I've tried installing it using conda and I get this message:

~ % conda install -c bioconda hybpiper
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - hybpiper

Current channels:

  - https://conda.anaconda.org/bioconda/osx-arm64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/default/osx-arm64
  - https://conda.anaconda.org/default/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/chrisjackson-pellicle/osx-arm64
  - https://conda.anaconda.org/chrisjackson-pellicle/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

A similar message shows up when I try to install with mamba. I've tried changing python versions as well (from 3.10 to 3.9), but the issue persists. I'm not a bioinformatician, so I'll need a more detailed explanation, if possible.

thank you

**Comment by chrisjackson-pellicle** [comment]
Hi @veronicamb,

I was just typing a response and noticed that you've closed this issue. Did you find a solution? Here's my partially completeed response, in case it's of any use:


"""
By the look of your current channel list, it appears as though you're using a Mac with an M1 or M2 chip with ARM64 architecture - is that correct?

If so, you won't be able to install HybPiper from bioconda, as bioconda doesn't support ARM64 architecture osX yet (see e.g. [here](https://github.com/conda/conda/issues/11216) and [here](https://github.com/bioconda/bioconda-recipes/issues/23454#issuecomment-1403511350) - looks like it _might_ arrive Q3 2023...). 

I'll be maintaining the latest HybPiper versions on my conda channel (https://anaconda.org/chrisjackson-pellicle/hybpiper) for a while, but unfortunately I don't have access to an M1 Mac to build and test the HybPiper package. However, it's my understanding that you can install x86 conda packages on an M1 Mac, e.g. see here: https://towardsdatascience.com/how-to-manage-conda-environments-on-an-apple-silicon-m1-mac-1e29cb3bad12
""""


Cheers,

Chris
