### ISSUE TITLE
Spades not running

### ISSUE THREAD

**Issue by willyard** [mossmatters/HybPiper#12]
I am a new user of HybPiper. When I run the reads_first_py, I get the following error and no spades files are created. All of my target genes are in the failed_spades.txt file. I have tried several ways to arrange the scripts and raw files and have tried 3 different samples. I have not located a list of files that should have been created at each step so that I can debug. I can see that a directory is created for the sample and that subdirectories for each gene are created that only has 2 files for each gene: gene010001_baits.fasta and gene010001_interleaved.fasta.

Traceback (most recent call last):
  File "/mnt/datos/HybPiper/spades_runner.py", line 166, in <module>
    if __name__ == "__main__":main()
  File "/mnt/datos/HybPiper/spades_runner.py", line 160, in main
    spades_failed,spades_duds = rerun_spades("failed_spades.txt",cov_cutoff=args
.cov_cutoff,paired=is_paired)
  File "/mnt/datos/HybPiper/spades_runner.py", line 82, in rerun_spades
    all_kmers = [int(x[1:]) for x in os.listdir(os.path.join(gene,"{}_spades".fo
rmat(gene))) if x.startswith("K")]
OSError: [Errno 2] No such file or directory: 'gene02157/gene02157_spades'
WARNING: Something went wrong with the assemblies! Check for failed assemblies a
nd re-run!
ERROR: No genes had assembled contigs! Exiting

Thank you for any ideas!
--Ann Willyard

**Comment by mossmatters** [comment]
If the first two stages-- read mapping and distribution-- are executed correctly you should have:

1. A .bam or .blastx file which lists the mapping results (SampleName.bam or SampleName.blastx)

2. A text file that lists the genes with reads mapping to the targets (spades_genelist.txt)

2. A file that lists the targets with successful hits (bait_tallies.txt)

2. A separate directory for each gene with hits.

From the errors it looks like spades was not able to run properly. Can you execute `spades.py` from the command line with out errors?

You can also check the spades.log file, which may have a clearer explanation about why spades failed.

Have you tried running the test dataset? 

https://github.com/mossmatters/HybPiper/wiki/Tutorial

This is the best way to make sure that all of the dependencies are installed and running properly. Let me know what you find!

**Comment by willyard** [comment]
Thank you, Matt.
I had run test data, but forgot to change my path to include spades for the real run. Having some spades files created lead me to believe that spades had started. I am pretty darned easy to confuse in a Unix environment. I appreciate you writing the scripts and you being kind enough to answer so quickly.
Best,
--Ann

**Comment by mossmatters** [comment]
No problem, let me know if you have any other issues. I'm only a couple of years removed from being a UNIX newbie myself, so I know how confusing it can get!
