### ISSUE TITLE
should --run_intronerate be on by default?

### ISSUE THREAD

**Issue by mossmatters** [mossmatters/HybPiper#124]
Is there any reason why `--run_intronerate` shouldn't be the default behavior in HybPiper2? Historically there was `intronerate.py` in HybPiper 1.3 but that isn't necessary anymore. Would there be a substantial effect on the FNA or GFF outputs if we just made it the default to recover supercontigs?

It does produce more files, but if that is an issue we could switch it to `--no-intronerate` instead...

**Comment by chrisjackson-pellicle** [comment]
@mossmatters As of version 2.1.5, Intronerate is now run by default, and the `hybpiper assemble` flag `--run_intronerate` has been changed to `--no_intronerate`.

**Comment by FrancisNge** [comment]
Hi Chris, Matt, just to clarify if I've interpreted this correctly, the loci included in the paralogs_all output folder will also now be based on the supercontigs as you mentioned --run_intronerate is now run by default for v2.1.5?

Cheers
Francis

**Comment by chrisjackson-pellicle** [comment]
Hi @FrancisNge,

No, the paralog output will not change. HybPiper recovers putative paralog/allele sequences via Exonerate hits to individual SPAdes contigs. The only difference with having Intronerate run by default is that supercontig and intron sequences will be generated by default.

Cheers,

Chris

**Comment by FrancisNge** [comment]
Hi @chrisjackson-pellicle ok thanks for clarifying. I'm just thinking how to get around this with using supercontigs while also accounting for paralogs. As I've been using the paragone pipeline to resolve paralogs and that takes the output from paralog_all from hybpiper, which I assume from above only contains exonerate hits (i.e., exons, and not introns).

Cheers
Francis
