### ISSUE TITLE
exonerate_contigs issue and less genes with seqs in v2.1.5?

### ISSUE THREAD

**Issue by joyceem** [mossmatters/HybPiper#126]
Hi Chris, 

As flagged in a [previous issue](https://github.com/mossmatters/HybPiper/issues/122#issuecomment-1639105450), I am getting a much lower number of genes with sequences using HybPiper v2.1.5 compared to v2.0. The number of genes mapped is the same in v2.1.5, but the number of genes with sequences is much lower than in 2.0 (~30% of what I get in v2.0). Additionally, as you mentioned there appears to be an issue with there being more genes at 25%. Seems to be something going on with exonerate?

I have attached a folder with a direct comparison of samples run with v2.0 vs. v2.1.5, with the log files, seq_lengths and stats output. These runs are with the same HybPiper settings, same target file and same samples for the A353 loci, but on different workstations with different versions of HybPiper. 

Please let me know if you need any more info, and thanks in advance for your time!!

[HybPiper2.0vs2.1.5.zip](https://github.com/mossmatters/HybPiper/files/12104539/HybPiper2.0vs2.1.5.zip)

Cheers,
Lizzy

**Comment by chrisjackson-pellicle** [comment]
Hi Lizzy,

Thanks for those files. The sample logs show that with your v2.1.5 runs, many more genes had failed SPAdes assemblies. That's odd, as the `ReadsMapped`, `PctOnTarget` and  `GenesMapped` values in the stats files are identical, so the reads going in to each SPAdes assembly should be the same in both HybPiper versions.

Can you upload the `spades.log` files for a couple of samples, for v2 and 2.1.5?

Cheers,

Chris

**Comment by joyceem** [comment]
Hi Chris,

Thanks for looking into this. Here are the SPAdes log files for three samples:
[2.0spades.zip](https://github.com/mossmatters/HybPiper/files/12106290/2.0spades.zip)
[2.1.5spades.zip](https://github.com/mossmatters/HybPiper/files/12106291/2.1.5spades.zip)

Cheers,
Lizzy

**Comment by chrisjackson-pellicle** [comment]
Ah yep, the SPAdes logs for v2.1.5 are full of the following types of errors:

```
[Errno 1] Operation not permitted: '/home/joyce/student_data_remote/monika/NGS_tree/3_hybpiper/MELI_Trichilia_americana_LEMJ299/5357/5357_spades/pipeline_state/stage_2_preprocess_finish'
Traceback (most recent call last):
  File "/home/joyce/applications/miniconda3/envs/hybpiper/bin/spades.py", line 634, in main
    executor.execute(commands)
  File "/home/joyce/applications/miniconda3/envs/hybpiper/share/spades/spades_pipeline/executors/executor_local.py", line 45, in execute
    self.touch_file(command, num)
  File "/home/joyce/applications/miniconda3/envs/hybpiper/share/spades/spades_pipeline/executors/executor_local.py", line 78, in touch_file
    open(path, 'a').close()
    ^^^^^^^^^^^^^^^
PermissionError: [Errno 1] Operation not permitted: '/home/joyce/student_data_remote/monika/NGS_tree/3_hybpiper/MELI_Trichilia_americana_LEMJ299/5357/5357_spades/pipeline_state/stage_2_preprocess_finish'
```

and 

```
0:00:00.314     1M / 25M   ERROR   General                 (mmapped_reader.hpp        :  41)   open(2) failed. Reason: Operation not permitted. Error code: 1. File: /home/joyce/student_data_remote/monika/NGS_tree/3_hybpiper/MELI_Trichilia_americana_LEMJ299/6457/6457_spades/tmp/spades_h3cm5nla/construction_iX4r1X/kmers_raw_oQUG6n.8
```

So, you've got permission errors of some sort. It's strange that they appear to be intermittent - SPAdes runs fine for some genes, at least. You mentioned that you ran v2 and v2.1.5 on different workstations - you might need to speak to the system administrator for the workstation you ran v2.1.5 on.

Or, you could just run v2.1.5 on the same workstation you ran v2 on, of course.

Oh, I just noticed that your SPAdes logs for v2 contain several errors too:

```
0:00:00.777     1M / 24M   ERROR   General                 (mmapped_reader.hpp        :  41)   open(2) failed. Reason: Operation not permitted. Error code: 1. File: /home/student/STUDENT_DATA_REMOTE/monika/NGS_tree/3_hybpiper/MELI_Trichilia_americana_LEMJ299/6780/6780_spades/tmp/spades_gujj5cn4/construction_MNjSbo/kmers_raw_8zqk0n.1.idx
```

However, these only occur four time compared to the hundreds of errors in the v2.1.5 SPAdes logs. Again, perhaps chat with the relevant sysadmin. I don't _think_ it's an issue related to HybPiper itself...

Cheers,

Chris

**Comment by chrisjackson-pellicle** [comment]
I'm closing this issue, but feel free to re-open it if it's still a problem!
