### ISSUE TITLE
Hybpiper Stats 

### ISSUE THREAD

**Issue by vicmmer** [mossmatters/HybPiper#128]
Hello, 

I am having an issue with the Hybpiper stats command.
This is my command: hybpiper stats -t_dna Angiosperms353_targetSequences.fasta gene namelist.txt

and this is the error I receive: UnboundLocalError: local variable 'mappedReads' referenced before assignment

What can I do about this? 

Thank you so much!

**Comment by chrisjackson-pellicle** [comment]
Hi @vicmmer,

Can you tell me to following:

1) Did you use BWA to map your reads  - i.e., did you run `hybpiper assemble` using the flag `--bwa`?

2) Did you install HybPiper using conda? If not, what version of samtools are you using?

3) If you did use BWA, can you move in to one of your sample directories and provide the output of the following command, replacing <your_sample_name> with the name of your specific sample:

    `samtools flagstat <your_sample_name>.bam`


Cheers,

Chris

**Comment by vicmmer** [comment]
Hello Chris, 

Thank you so much for getting back to me. I truly appreciate your help on this matter. To answer your questions: 

1) Yes, i used BWA to map my reads, this was my command used for each of my 96 samples: hybpiper assemble -t_dna Angiosperms353_targetSequences.fasta -r VM20_Astragalus_camptopus_L1_*_trimmed.fq --prefix VM20_Astragalus_camptopus --bwa

2) I did not have to install HybPiper as it is already available through the server I am using. I am using the 2.0.1 version of HybPiper though, (how do I check which is the associated samtools version?). 

3) When I try that command you gave me this is the output: 
samtools flagstat VM96_Astragalus_nikitinae.bam:
11171044 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
22204 + 0 supplementary
0 + 0 duplicates
3545935 + 0 mapped (31.74% : N/A)
11148840 + 0 paired in sequencing
5574420 + 0 read1
5574420 + 0 read2
3253548 + 0 properly paired (29.18% : N/A)
3279004 + 0 with itself and mate mapped
244727 + 0 singletons (2.20% : N/A)
21236 + 0 with mate mapped to a different chr
16996 + 0 with mate mapped to a different chr (mapQ>=5)

**Comment by chrisjackson-pellicle** [comment]
Hi @vicmmer,

Ah, I can see from your `samtools flagstat` output that you're using a samtools version that's less than version 1.14 (the minimum required by HybPiper, see [here](https://github.com/mossmatters/HybPiper/wiki/Installation#dependencies)). 

You'll need to ask your server systems administrator to update your samtools version. Also, I _highly_ recommend that you update HybPiper to the latest version (currently 2.1.6), as version 2.0.1 contains several bugs that can affect the sequences recovered.

Cheers,

Chris

**Comment by chrisjackson-pellicle** [comment]
Hi @vicmmer,

Did you get this fixed? If so, I'll close the issue.

Cheers,

Chris

**Comment by chrisjackson-pellicle** [comment]
I'm closing this issue, but feel free to re-open it if it's still a problem!
