### ISSUE TITLE
 Lower Intron Recovery by HybPiper v2.0?

### ISSUE THREAD

**Issue by ZhiqiongMo** [mossmatters/HybPiper#129]
Hello!

In my recent analyses, I utilized both HybPiper v2.0 and HybPiper v1.3 to recover intron sequences. However, I observed that the number of introns and completeness obtained using HybPiper v2.0 is significantly lower than that of HybPiper v1.3, while both versions yield high completeness of exons (as shown in the heatmap.).
I would like to know if there have been changes in v2.0 or if there might be an issue with my usage. 

The command of v1.3:
reads_first.py -r sample1_1.fq sample1_2.fq -b ref.fa --prefix sample1 --bwa --cpu 2
intronerate.py --use_target --addN --prefix sample1

The command of v2.0:
hybpiper assemble -r  sample1_1.fq sample1_2.fq -t_dna ref.fa --prefix sample1 --bwa --run_intronerate --cpu 2 --distribute_hi_mem

thank you!

![heatmap](https://github.com/mossmatters/HybPiper/assets/144522313/9e95bff3-a472-4991-bb39-f28917dbe70d)

**Comment by chrisjackson-pellicle** [comment]
Hi @ZhiqiongMo,

Yes, there is a difference in the way HybPiper recovery introns in version 2, compared to version 1.3. The method HybPiper 2 uses is described [here](https://github.com/mossmatters/HybPiper/wiki/Introns) (see Note 2).

HybPiper identifies introns via Exonerate searches, using the translated protein sequence of the exon-only sequence as a query, and the nucleotide sequence of the supercontig (i.e. exons _and_ introns) as the subject. HybPiper 1.3 reported _any_ region of the supercontig without a hit to the protein query as an 'intron'. HybPiper v2, on the other hand, only reports introns that occur in between detected exons, as there's no guarantee that the query protein is full length, and we don't want flanking exonic regions in the raw SPAdes contigs being annotated as introns by mistake.

Also, I see that you're using an older version of HybPiper 2. I strongly recommend updating to the most recent version (currently 2.1.6), as earlier versions contains several bugs that can affect the sequences recovered.

Cheers,

Chris

**Comment by ZhiqiongMo** [comment]
I see. Thanks for your explanation. I will try the latest version for analysis.
