### ISSUE TITLE
Hybpiper not available from installed channels

### ISSUE THREAD

**Issue by wtesto** [mossmatters/HybPiper#133]
Hi guys - 

I am currently trying to install HybPiper on a new computer (2021 iMac with M1 chip; macOS Ventura 13.4) and have run into a problem installing with conda using the commands provided on this repo. I have no problem adding the required channels, but when I run 

`conda install -c chrisjackson-pellicle hybpiper`

I get the following error: 

**Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - hybpiper

Current channels:

  - https://conda.anaconda.org/chrisjackson-pellicle/osx-arm64
  - https://conda.anaconda.org/chrisjackson-pellicle/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/osx-arm64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch**

Is this a case where something has been updated recently on your end, or might there be a python version incompatibility (see this  issue on another repo: [https://github.com/conda/conda/issues/12206](url)?

**Comment by mossmatters** [comment]
Weston,

Sorry you're having troubles - it looks like we may need to update the README. Now that [HybPiper is on bioconda](https://bioconda.github.io/recipes/hybpiper/README.html) you can replace Chris' conda repo in the install command:

`conda install -c bioconda hybpiper`

Let us know if you have further issues!

**Comment by wtesto** [comment]
Hi Matt,

Thanks for this. 

It turns out that the issue that I had was that bioconda was not compiling correctly with the osx-arm64 architecture that was setup on my computer. I had to switch back to a x86_64 architecture, and then things worked. Thanks!
