### ISSUE TITLE
Warning more than one Exonerate hit

### ISSUE THREAD

**Issue by pablomurod** [mossmatters/HybPiper#140]
Hi Matt,

I have been using HybPiper for a long time now. I recently updated to version 2.1.6 and started receiving a warning that there is more than one exonerate hit for a given node in a given gene. I paste an example at the end. 

The sequences in the target file include sequences with low complexity regions (I am using --timeout_assemble 200) and with internal stop codons. They do not correspond exactly to genes. I did not have this warning with previous HybPiper versions and the same data and target file; the assembly always looked all right. The assembly now also seems to finish all right, although several samples and genes throw the warning. I am not sure what I need to do, if anything...

`[WARNING]: There is more than one Exonerate hit for NODE_2_length_1536_cov_26.057394 for gene Solyc075930, sample Ipomoea_JR_245, but these do NOT appear on the same strand. CHECK THIS! Intron and supercontig sequences will not be recovered.`

I would appreciate any comments
Thanks in advance!
Pablo

**Comment by chrisjackson-pellicle** [comment]
Hi @pablomurod,

I added this warning as part of the re-write of the `exonerate_hits.py` module for HybPiper version 2.  

As described [here](https://github.com/mossmatters/HybPiper/wiki/Troubleshooting,-common-issues,-and-recommendations#13-target-files-with-protein-coding-nucleotide-sequences-in-the-wrong-frame), HybPiper translates the 'best' target file sequence for a given gene/locus, and uses Exonerate to align the translated protein sequence to the sample nucleotide contigs (the latter are assembled with SPAdes). The most common use-case is where the target file sequences correspond to standard protein-coding genes. In this scenario, if there are multiple alignments between a given target file protein and a sample contig (e.g. corresponding to the 5' and 3' halves of the gene) it is expected that they would both be from the same contig strand. One scenario where this expectation might not hold is if the target file sequence contains an inverted repeat - is that the case, for your sequences?

When HybPiper 2 creates the main nucleotide output sequence for a given target file gene/locus, it doesn't care if there are multiple Exonerate alignments to different strands of a given SPAdes contig - it simply chooses the 'best' alignment and uses that. However, when generating a supercontig sequence (i.e. containing both exons and intron sequence) this becomes more problematic, and so HybPiper throws the warning you're seeing. HybPiper uses the intron-aware 'protein2genome' model to delineate exon vs intron coding sequence, under the assumption that the target sequences contain in-frame protein-coding exonic sequence only. Given that's not the case for your target file sequences, I expect you're ignoring the 'intron' and 'supercontig' output anyway (?), and so you can likely safely ignore the warning you're seeing.  

If you want to look at the Exonerate alignments more closely to see exactly what's happening, you could examine e.g. the file  `Ipomoea_JR_245/Solyc075930/Ipomoea_JR_245/exonerate_results.fasta` (see [here](https://github.com/mossmatters/HybPiper/wiki/Results-and-output-files#base-directory---gene-directory---exonerate-directory) for a full list of output files).

Let me know if the above isn't clear, or if you need any more info!

Cheers,

Chris

**Comment by pablomurod** [comment]
Hi Chris, thanks for the detailed reply!

I do not think my target file sequences contain inverted repeats, but I'll check again just in case. You are right I retrieve genes, not introns or supercontigs, and the gene sequences seem as good as with previous HybPiper versions. I will have a close look to the exonerate files anyway to understand this in full.

Thank you again!
Pablo
