### ISSUE TITLE
Depreciation of Bio.Application 

### ISSUE THREAD

**Issue by mossmatters** [mossmatters/HybPiper#147]
A user reported seeing a warning associated with the use of Bio.Application:

```
/home/petzold1/miniconda3/envs/hybpiper/lib/python3.11/site-packages/Bio/Application/__init__.py:40: BiopythonDeprecationWarning: The Bio.Application modules and modules relying on it have been deprecated.

Due to the on going maintenance burden of keeping command line application 
wrappers up to date, we have decided to deprecate and eventually remove these
modules.

We instead now recommend building your command line and invoking it directly
with the subprocess module.
warnings.warn( 
```

According to the [Bio.Application documentation](https://biopython.org/docs/latest/api/Bio.Application.html), this warning is now indicating that the module is now obsolete.

I suspect the call that triggers the warning has to do with Bio.SearchIO for exonerate, but it is worth looking into!

**Comment by chrisjackson-pellicle** [comment]
This warning is only for `Bio.Application` command line wrappers like `NcbiblastpCommandline`, `Bio.Align.Applications.MafftCommandline` etc., so `Bio.SearchIO` isn't effected.

In HybPiper 2 this warning is being triggered by the import of `Bio.Align.Applications.MafftCommandline` in the `fix_targetfile.py` module. No other HybPiper module uses a BioPython command line wrapper. I'll change this to call `mafft` directly in the next update, but for now it can safely be ignored!

**Comment by chrisjackson-pellicle** [comment]
Fixed
