### ISSUE TITLE
Tutorial Heat Map

### ISSUE THREAD

**Issue by Gabriel-P-Johnson** [mossmatters/HybPiper#149]
I am brand new to working with HybPiper and am working through the tutorial. 
The heat map I generated is rather different form that shown int he tutorial, even though I was using the same dataset.
Why?
I have attached my heatmap along with by .log file for EC30 which shouldn't have had any missing genes.
I suspect there is a very obvious and simple answer that I cannot see.
Thank you for whatever help you can provide.
Regards, 
Gabe

![recovery_heatmap](https://github.com/mossmatters/HybPiper/assets/173510606/25667f64-e21f-4bb4-948b-d4b4ed16e705)
[EG30_hybpiper_assemble_2024-06-21-16_49_54.log](https://github.com/user-attachments/files/15934089/EG30_hybpiper_assemble_2024-06-21-16_49_54.log)

**Comment by chrisjackson-pellicle** [comment]
Hi @Gabriel-P-Johnson,

I've just run the test dataset with HybPiper v2.1.6 following the tutorial, and can confirm that the heatmap looks the same as as that in the tutorial. 

Your log from sample EG30 shows that the `hybpiper assemble` command didn't run to completion, and only processed 9 of the 13 genes in the test data. Your log file should end with:


```
[INFO]:    Generated sequences from 13 genes!
2024-06-22 17:36:08,576 - assemble.py - hybpiper.assemble - assemble - INFO - [WARNING]: Potential long paralogs detected for 0 genes!
2024-06-22 17:36:08,576 - assemble.py - hybpiper.assemble - assemble - INFO - [WARNING]: Potential paralogs detected via contig depth for 2 genes!
2024-06-22 17:36:08,576 - assemble.py - hybpiper.assemble - assemble - INFO - 
Finished running "hybpiper assemble" for sample EG30!
``` 

There's no error in the log file to indicate that something went wrong with HybPiper internally - were there any messages printed to your screen when you ran the command?

Cheers,

Chris

**Comment by Gabriel-P-Johnson** [comment]
Hi Chris,
Thank you so very much for getting back with me so quickly. Attached is the whole output folder from EG30 with a variety of log files that might have the answer.
When I ran the job on the computer cluster here at the Smithsonian it did not give me any errors printed to screen (at least that I was aware of).
I have the jobs 7 hours with 1 GB of memory and they usually completed in less than 1 minute, so the jobs must have been aborting prematurely.
Thank you so very much again,
Gabe

[https://res-h3.public.cdn.office.net/assets/mail/file-icon/png/generic_16x16.png]EG30.tar<https://sinet-my.sharepoint.com/:u:/g/personal/johnsong_si_edu/EenWDfbjt2dBuIW9dTds9mgBuaNxefkEQeHQf4lMpruBpg>


Gabriel Johnson

Laboratory Technician
Smithsonian Institution
Museum Support Center
4210 Silver Hill Road
Suitland, Maryland  20746
301-238-1098
________________________________

**Comment by Gabriel-P-Johnson** [comment]
Hi Chris,
I attempted to send the .tar file to your rbg.vic.gov.au email address. Let me know if you received it.
Int he meantime, I re-ran the EG30 sample hyb-piper assembly and received the attached error file (My institutions computer cluster requires and extra command ot have the error output go to a separate error log. Supposedly these errors were included in the log file of my original run).
Many thanks,
Gabe




Gabriel Johnson

Laboratory Technician
Smithsonian Institution
Museum Support Center
4210 Silver Hill Road
Suitland, Maryland  20746
301-238-1098
________________________________

**Comment by chrisjackson-pellicle** [comment]
Hi Gabe,

I received your run data for sample EG30. It all looks normal, other than the fact that it didn't complete.

I can't see your attached error files - you'll need to upload them via this issue page on the HybPiper git repo webpage, as they won't appear if you're replying via email.

Cheers,

Chris

**Comment by Gabriel-P-Johnson** [comment]
Oh OK. Sorry about that.
Attached is the .err file.
-Gabe
[EG30_test_err.txt](https://github.com/user-attachments/files/15990373/EG30_test_err.txt)

**Comment by Gabriel-P-Johnson** [comment]
I received word from the informatics office here that I did not allocate enough memory for these jobs to run to completion. I used 1 G for 7h; instead, I should have used 8G.
Thank you so very much for your help.

**Comment by chrisjackson-pellicle** [comment]
No worries - glad it's working!
