### ISSUE TITLE
Question about .blastx files

### ISSUE THREAD

**Issue by wojahn** [mossmatters/HybPiper#151]
Hello,
I ran HybPiper with the following arguments:

hybpiper assemble -r ${sample}*.fastq --targetfile_aa translated_Baits.fasta --prefix ${sample} --cpu ${result} --merged --hybpiper_output HybOut

and it worked perfectly. However, when moving the files to my main storage disk I mistakenly deleted the .blastx files in the results, and therefore the stats function will not work. Is there a way for me to re-generate the .blastx files without having to run the full HybPiper analysis on those samples again?
Thank you for your help,
Michael

**Comment by wojahn** [comment]
Figured it out :)

while read sample_name
do
  
  makeblastdb -dbtype prot -in translated_Baits.fasta # from assemble
  
  cat ${sample_name}_R1_001_P.fastq | awk '{if(NR % 4 == 1 || NR % 4 == 2) {sub(/@/, ">"); print; } }' | parallel -j 30 -k --block 200K --recstart '>' --pipe 'blastx -db translated_Baits.fasta -query - -evalue 0.0001 -outfmt 6 -max_target_seqs 10' >> ${sample_name}.blastx # from assemble
  
  cat ${sample_name}_R2_001_P.fastq | awk '{if(NR % 4 == 1 || NR % 4 == 2) {sub(/@/, ">"); print; } }' | parallel -j 30 -k --block 200K --recstart '>' --pipe 'blastx -db translated_Baits.fasta -query - -evalue 0.0001 -outfmt 6 -max_target_seqs 10' >> ${sample_name}.blastx # from assemble
  
done < ReBlastx.txt # the samples I accidentally deleted blastx files for

# then move to corresponding sample directory

**Comment by chrisjackson-pellicle** [comment]
Nice!
