### ISSUE TITLE
Issues installing - TypeError: main() missing 1 required positional argument: 'args'

### ISSUE THREAD

**Issue by ksanb** [mossmatters/HybPiper#153]
Hi y'all, I've followed the recommended installation, and have activated the hybpiper conda environment.

When I call the function hybpiper I get the following error:

Traceback (most recent call last):
  File "/Users/ranunculus/miniconda3/envs/hybpiper/bin/hybpiper", line 10, in <module>
    sys.exit(main())
             ^^^^^^
TypeError: main() missing 1 required positional argument: 'args'

I've tried installing it both on an M1 (following the special instructions to do so) and on an intel. This makes me think I'm doing something wrong here.

**Comment by chrisjackson-pellicle** [comment]
Hi @ksanb,

My fault - I hadn't updated the recipe on Bioconda for HybPiper v2.2.0. 

A Bioconda package gets built automatically when a new release is made, but I'd made some changes in v2.2.0 that required manual intervention. I've updated the recipe and made a pull request (https://github.com/bioconda/bioconda-recipes/pull/49428) - it should be fixed within a couple of hours.

Cheers, 

Chris

**Comment by ksanb** [comment]
Chris,

Thanks so much! It's working now.

Cheers,
-Katie
