### ISSUE TITLE
hybpiper fix_targetfile

### ISSUE THREAD

**Issue by oliviermaurin** [mossmatters/HybPiper#156]
Hi Matt, 
Hope all is well. I am having an issue which may well be an install problem from my side but cannot get my head around it.
I am running hybpiper fix_targetfile with basic settings, I have done _hybpiper check_dependencies_ and mafft is listed, but I get the following error when running hybpiper fix_targetfile: 
_NameError: name 'MafftCommandline' is not defined_
can you please advise if possible? am I missing something embarassigly obvious?
Good day
Olivier
<img width="1157" alt="Screenshot 2024-08-23 at 02 55 06" src="https://github.com/user-attachments/assets/d24db1d5-f3eb-4fd1-92ab-6f5af1b27b4b">
<img width="674" alt="Screenshot 2024-08-23 at 02 54 34" src="https://github.com/user-attachments/assets/070b3fc7-a7f1-43de-a2ce-19d9b3265043">

**Comment by chrisjackson-pellicle** [comment]
Hi @oliviermaurin,

This one is my fault -  I didn't update all the MAFFT commands when removing reliance on the BioPython command line wrappers (`Bio.Align.Applications.MafftCommandline`, in this case) for HybPiper version 2.1.8 (see [here](https://github.com/mossmatters/HybPiper/issues/147) and [here](https://github.com/mossmatters/HybPiper/blob/master/change_log.md)).

I'll fix this is the next HybPiper version (hopefully within a couple of weeks). In the meantime, if you install HybPiper version 2.1.7 in a new conda environment the command should run as expected. Sorry for the hassle!

Cheers,

Chris

**Comment by oliviermaurin** [comment]
thank you so much Chris . much appreciated

**Comment by chrisjackson-pellicle** [comment]
Fixed in HybPiper version 2.3.0
