### ISSUE TITLE
`hybpiper stats` and `hybpiper retrieve_sequences` take a very long time when processing compressed sample folders (HybPiper version 2.3.0)

### ISSUE THREAD

**Issue by chrisjackson-pellicle** [mossmatters/HybPiper#161]
Stats and sequence recovery commands take a very long time when processing compressed (`*.tar.gz`) sample files with HybPiper version 2.3.0

**Comment by chrisjackson-pellicle** [comment]
Known issue - each compressed sample file should only be uncompressed once, and sample files should be processed in parallel using multiprocessing. Currently working on a fix for HybPiper version 2.3.1

**Comment by BenKuhnhaeuser** [comment]
Thank you for working on this, was caught by this one recently! So pleased that you are implementing the ability to work with compressed file directories as backups of the many many folders and subfolders generated by HybPiper are computationally so expensive.

**Comment by chrisjackson-pellicle** [comment]
Fixed (...) - now available in HybPiper version 2.3.1. The bioconda build should be available in a couple of hours.

On 100 samples assembled using the Angiosperms353 target file, `hybpiper stats` now finishes in about 45 minutes using `--cpu 100`, whereas `hybpiper retrieve_sequences` takes about 19 minutes (AMD EPYC 7601 2700 MHz).
