### ISSUE TITLE
Parallelisation of retrieve_sequences and stats

### ISSUE THREAD

**Issue by BenKuhnhaeuser** [mossmatters/HybPiper#162]
For a large number of samples and genes (in my case, 1000 samples, 3700 genes), the `retrieve_sequences` and `stats `commands takes days to run (I'm at 700 genes after 24 h). My workaround was to split the targetfile into 3700 "one-gene" targetfiles and run `retrieve_sequences` in parallel for each gene, which only takes a few minutes for each gene. But this is certainly not the most elegant solution, and I haven't managed yet to parallelise the `stats `command.

Would it be possible to implement such parallelisation for both commands in a future version by making use of multiple cores?

Many thanks for your consideration and hard work.
Ben

**Comment by chrisjackson-pellicle** [comment]
Hi @BenKuhnhaeuser,

Ha, yes, I see you've seen the issue I raised as well. I've finished the re-write of `hybpiper stats` - working on `retrieve_sequences` and `paralog_retriever` now. 

The `stats` command now processes 4 samples (`*.tar.gz` file sizes ranging from 161 mb to 1 gb) in 145 secs using 1 thread, or 96 secs using 4 threads, whereas I quit the command using HybPiper version 2.3.0 as it hadn't finished after 15 minutes. Oops, should've tested that more thoroughly...

Cheers,

Chris

**Comment by BenKuhnhaeuser** [comment]
Perfect, thank you!

**Comment by chrisjackson-pellicle** [comment]
Finished - now available in HybPiper version 2.3.1. The bioconda build should be available in a couple of hours.

On 100 samples assembled using the Angiosperms353 target file, `hybpiper stats` now finishes in about 45 minutes using `--cpu 100`, whereas `hybpiper retrieve_sequences` takes about 19 minutes (AMD EPYC 7601 2700 MHz).

Let me know if there are any issues!

Cheers,

Chris
