### ISSUE TITLE
ERROR: No genes with BLAST hits! Exiting!

### ISSUE THREAD

**Issue by BrianaGross** [mossmatters/HybPiper#18]
I've installed HybPiper and gotten it to work on the test data, and on a 'test' subset of my own data - that is, I can get it to work for one sample (one set of fastq files) and a couple genes as targets. When I attempt to scale this up to using a 'names.txt' file and "while" loop, the program exits just before running SPAdes (I think). This is still at a low level - I have only two individuals and still two genes in the target file. Both individuals make it successfully through the pipeline if I call the pipeline just for them.  

Here is my command (just like your tutorial): 
`while read name; 
do ../reads_first.py -b Full_2Gene.txt -r "$name*.fastq" --prefix $name --bwa; 
done < namelist.txt`

Here is the program output ending in the error, but I've taken out some of the mem stuff to shorten it:
Making nucleotide bwa index in current directory.
[CMD]: bwa index Full_2Gene.txt
[bwa_index] Pack FASTA... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.00 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.00 sec
[main] Version: 0.7.13-r1126
[main] CMD: bwa index Full_2Gene.txt
[main] Real time: 0.007 sec; CPU: 0.008 sec
[CMD]: time bwa mem -t 8 Full_2Gene.txt /Users/brianagross/HybPiper/malus_test06/002or*.fastq  | samtools view -h -b -S - >  002or.bam
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 890654 sequences (80000015 bp)...
[M::process] read 891318 sequences (80000039 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 454, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
...
[M::mem_pestat] low and high boundaries for proper pairs: (1, 715)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 17116 reads in 0.855 CPU sec, 0.127 real sec
[main] Version: 0.7.13-r1126
[main] CMD: bwa mem -t 8 Full_2Gene.txt /Users/brianagross/HybPiper/malus_test06/002or_1P.fastq /Users/brianagross/HybPiper/malus_test06/002or_2P.fastq
[main] Real time: 43.760 sec; CPU: 137.596 sec

real	0m43.802s
user	2m49.029s
sys	0m2.194s
[CMD] time python /Users/brianagross/HybPiper/distribute_reads_to_targets_bwa.py 002or.bam /Users/brianagross/HybPiper/malus_test06/002or*.fastq

Unique reads with hits: 1673

real	0m17.094s
user	0m14.206s
sys	0m0.437s
/usr/local/lib/python2.7/site-packages/Bio/Seq.py:2071: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  BiopythonWarning)
0 proteins had no good matches.

real	0m2.403s
user	0m2.137s
sys	0m0.078s
ERROR: No genes with BLAST hits! Exiting!

I am sure there is something that I'm missing in there - do you see something obvious?

Many thanks for sharing this software,
Briana

**Comment by mossmatters** [comment]
It does look like HybPiper got stuck between the mapping stage and the contig assembly stage. This is when the reads and target sequences are distributed to different directories to prepare for assembly.

`distribute_reads_to_targets.py` is reporting that all of your target genes had mapping hits, and that there were 1673 reads with hits. Those reads should be distributed to the different gene directories, but then `reads_first.py` is unable to find those files.

If you descend into the `malus_test06` directory, inside each of the gene directories, is there a file `geneName_interleaved.fasta`? 

That should provide some clue, so let me know!

**Comment by BrianaGross** [comment]
Thanks for the quick reply! The `geneName_interleaved.fasta` files have been created inside the gene directory for the first sample in the list (second sample hasn't been processed, I think). The files do have reads in them, so everything seems good there.

**Comment by mossmatters** [comment]
All right, I am guessing that something isn't getting named correctly. Would you mind sharing the contents of `namelist.txt` and the contents of the directory where you're calling the while loop?

**Comment by BrianaGross** [comment]
Sure. I've attached the `namelist.txt`. The directory where I'm calling the loop is malus_test06, which is nested in the HybPiper directory. The directory contains: 002or_1P.fastq, 002or_2P.fastq, 012sy_1P.fastq, 012sy_2P.fastq, Full_2Gene.txt, namelist.txt (and then also the 002or directory that HybPiper made when it was working on the first sample). Let me know if there is an easier way for me to show or give you the files.
[namelist.txt](https://github.com/mossmatters/HybPiper/files/765190/namelist.txt)

**Comment by mossmatters** [comment]
I've at least figured out one issue-- You will need to add a new line to the end of  `namelist.txt` 

This explains why the while loop did not keep going to the second sample when the first one "finished". Just a quirk of doing loops in `bash`. So, some progress!

Could you share the 002or directory with me? You can just compress the directory and add the file on here. Since it's only a couple of genes, the file shouldn't be too large as a ZIP file. If the first part of the script executed properly I shouldn't need the reads to continue troubleshooting. Thanks!

**Comment by BrianaGross** [comment]
Okay, I can see that the new line character fixed the problem of progression to the next sample - thanks! The pipeline is still not producing the contig files (it now gives the `ERROR: No genes with BLAST hits! Exiting!` for both files), so I've gone ahead and attached the zipped 002or directory for you here. 

Thanks for your time on this. If you begin to suspect that this is something about my local set-up (I'm running this on my Mac desktop right now), please let me know - I'm also in the process of trying to get everything set up on my university supercomputer, so the environment will change soon.

[002or.zip](https://github.com/mossmatters/HybPiper/files/768962/002or.zip)

**Comment by mossmatters** [comment]
The ZIP file you posted is only 162 bytes and appears empty. Could you post it again? Thanks!

**Comment by BrianaGross** [comment]
Oops. Sorry! Here is the zipped directory containing everything except the BAM file - I couldn't get the BAM to compress to a small enough size to upload. Thanks for your patience.
[002or_NoBam.zip](https://github.com/mossmatters/HybPiper/files/771666/002or_NoBam.zip)

**Comment by mossmatters** [comment]
I figured it had to be something with the `while` loop because the script executes just fine without it. The issue is with the double quotes in the loop. For example:

`while read name; do echo "$name*.fastq"; done < namelist.txt`

Results in:
```
002or*.fastq
012sy*.fastq
```

**Comment by BrianaGross** [comment]
Wow - I inserted the double quotes somewhere along the way and had no idea of their effect. Thanks for your patience in helping me with this self-made problem!

**Comment by mossmatters** [comment]
No worries, happy to help! The example `while` loop in the wiki does have double quotes, which I have now removed. In my experience the quotes are only necessary in `bash` when you are working with a variable plus a file name with an underscore in it. Let me know if you have any other issues!
