### ISSUE TITLE
`--unpaired` causes spades to fail for baits with no unpaired reads

### ISSUE THREAD

**Issue by Perugolate** [mossmatters/HybPiper#24]
When using the `--unpaired` flag hybpiper tries to run all the spades assemblies for each gene like this:

```
time parallel --eta spades.py --only-assembler --threads 1 --cov-cutoff 8 -s {}/{}_unpaired.fasta --12 {}/{}_interleaved.fasta -o {}/{}_spades :::: spades_genelist.txt > spades.log
```

However `{}/{}_unpaired.fasta` does not exist for genes which have no mapped unpaired reads. This causes spades to fail for these genes. e.g.:

```
== Error ==  file not found: /media/tera5/katy/hyb_unp/fenzlii/fenzlii/At2g33340/At2g33340_unpaired.fasta (single reads, library number: 1, library type: paired-end)
```

spades will accept an empty file for `{}/{}_unpaired.fasta` so I will implement a call to `touch` as a workaround in the meantime.

**Comment by mossmatters** [comment]
Fixed in f42802d4578793ae0c4ea03e8a2a890df326cc6c, will be added to master in next release
