### ISSUE TITLE
exonerate_hits.py: Apparent execution path that misses canonicalisation of orientation

### ISSUE THREAD

**Issue by jttkim** [mossmatters/HybPiper#27]
The loop headed in line 155 iterates over contigs and canonicalises their orientation (line 164) to "+". However, if there is only one contig, its sequence is returned without ever checking for orientation. As contigs can come out of assemblers in either orientation, it seems possible that returning via line 153 results in returning a sequence in "-" orientation.

**Comment by mossmatters** [comment]
Fixed in 1.3! There is now also check for strand when there is only one hit.
