### ISSUE TITLE
exonerate_hits.py: Hard-coded percent sequence identity threshold

### ISSUE THREAD

**Issue by jttkim** [mossmatters/HybPiper#28]
In line 110, the condition `if float(i.id.split(",")[4])>55` seems to filter for percent sequence identity. Elsewhere in the script, the threshold is provided as a variable `thresh` (line 91), specified via the `--threshold` option. The filtering in line 110 may be unnecessary (assuming that contigs are always processed through `filter_by_percentid` prior to being fed to `supercontig_exonerate`). In this case it can be removed. Otherwise, the threshold will need to be added as a parameter to `supercontig_exonerate`, and upstream functions / method have to be updated accordingly.

**Comment by mossmatters** [comment]
Fixed in fa79bc8dff8eed25095f251c70e5eab265518035 and should be in version 1.3
