### ISSUE TITLE
hybpiper_stats.py - percent reads on target miscalculated with some samtools versions

### ISSUE THREAD

**Issue by weiserhardt** [mossmatters/HybPiper#30]
With samtools 0.1.19 installed, hybpiper_stats.py extracts the number of fwd reads instead of the number of mapped reads from the samtools flagstat output, leading to a wrong percentage of reads on target being calculated. I suspect this is a version issue caused by the fact that the script accesses the flagstat output by row number, and the order of rows differs among samtools versions.

**Comment by mossmatters** [comment]
Sorry for the (very) late reply. I think the best thing to do is to require samtools > 1.2 for future versions of HybPiper, as the pre-1.0 versions are now more than 5 years old.

**Comment by Cactusolo** [comment]
Just follow up, "hybpiper_stats.py" is not compatible with version of samtools, like  samtools/1.9. If you use samtools/1.9, the "hybpiper_stats.py"  will generate error as below:
`
[cactus]$ hybpiper_stats.py Cactus15seq_length.txt Cactus15namelist.txt
Name    NumReads        ReadsMapped     PctOnTarget     GenesMapped     GenesWithContigs        GenesWithSeqs   GenesAt25pct    GenesAt50pct    GenesAt75pct      Genesat150pct   ParalogWarnings
/bin/sh: 1: samtools: not found
Traceback (most recent call last):
  File "/apps/hybpiper/1.2/bin/hybpiper_stats.py", line 153, in <module>
    if __name__ == "__main__":main()
  File "/apps/hybpiper/1.2/bin/hybpiper_stats.py", line 130, in main
    stats_dict[name] += enrich_efficiency_bwa(bamfile)
  File "/apps/hybpiper/1.2/bin/hybpiper_stats.py", line 41, in enrich_efficiency_bwa
    numReads = float(flagstat_results[0].split()[0])
IndexError: list index out of range
`
