### ISSUE TITLE
Trouble with test dataset

### ISSUE THREAD

**Issue by TARobison** [mossmatters/HybPiper#31]
Hi,
First off, I apologize for my ignorance. I read the wiki and the tutorial and I still can't figure what I'm doing wrong. 

I'm running the test dataset and I keep running into the same problem. When I use get_seq_lengths.py it outputs the first and second lines like you would expect, but every other line only has zeros in the columns. I couldn't figure out what I was doing wrong so I ran again, this time using the run_tests.sh script and got the same results. 

I hope that is enough information.

**Comment by mossmatters** [comment]
`get_seq_lengths.py` needs to be run from the same directory as the output directories from HybPiper. It uses the names in `namelist.txt` to check for directories with those same names in the current directory. If these directories have been moved, or you are not in the correct directory, it will output zeroes. Hope this helps!

**Comment by TARobison** [comment]
Thanks for the help! I had I guess made a mistake in the command line and hybPiper had only partially run or something. When I did a fresh run I no longer had the problem.
