### ISSUE TITLE
Heat map cleanup

### ISSUE THREAD

**Issue by Wolflab** [mossmatters/HybPiper#34]
Matt: Here is the code I used for the heatmap, using ggplot. This worked on  25 taxa and 25 genes. no idea of scalability. I will email you the input file I used.

#require(gplots)
#require(heatmap.plus)

##  Set working directory to source file location
setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) # only for RStudio

#Here, set the file name of the table generated by get_seq_lengths.py
sample.filename = "all25concat-bases-count-matrix_names.tab"

#You should not need to change anything below this line!
#-------------------------------------------------------

#########################

library(ggplot2)
library(reshape2)

sample.data= as.matrix(read.table(sample.filename,header=T,row.names=1))
sample.len = sample.data[2:nrow(sample.data),]
reference.len = as.numeric(sample.data[1,])

#Calculate the percentage length recovered relative to the reference.
percent.len=sweep(sample.len,2,as.numeric(reference.len),'/')
percent.len = ifelse(percent.len>1,1,percent.len)
percent.long = melt(percent.len)

ggplot(data = percent.long, aes(x=Var2, y=Var1, fill = value))+
  geom_raster()+
  #guides(fill=FALSE)+ #remove this line if you want the heat scale to appear
  scale_fill_gradient(high = "#132B43", low = "#56B1F7")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  ylab(NULL)+xlab(NULL)+
  theme(axis.text.y=element_text(face="italic"))
ggsave("fern_gene_refined_scale_names.png", height = 4, width = 6, units = "in")

############

**Comment by mossmatters** [comment]
The new script is a lot cleaner with ggplot and seems to scale well to very large datasets. I edited some of the script to attempt an automatically resized sample and gene names. I will also put in a few examples of color schemes in the next update.

[bigheatmap.pdf](https://github.com/mossmatters/HybPiper/files/1388023/bigheatmap.pdf)

**Comment by mossmatters** [comment]
I have added `gene_recovery_heatmap_ggplot.R` to the repository. It is much simpler and works well, but I am having issues saving the image as a PDF. On my Mac it renders the image with very poor resolution, and is not "vectorized" like the output from baseR graphics. That may be fine if you can generate a publication-ready image with the PNG, but I'm keeping both scripts in case that matters to others.

**Comment by Wolflab** [comment]
Matt: I find the same issue and now generally save R plots to PNG. I find the PNG to pdf conversion in Preview (on Mac) is very good

No word yet on fern Target sequence capture paper

Paul
