### ISSUE TITLE
distribute_reads_to_targets_bwa.py: progress meter

### ISSUE THREAD

**Issue by biomendi** [mossmatters/HybPiper#36]
Hi Matt,

`distribute_reads_to_targets_bwa` is taking super long in some of my samples. Would it be possible to add a progress meter (or maybe a counter) in order to know how much time / sequences left to finish? I tried to do it but I am not exactly sure where to add the counter. I think this should be pretty trivial for you. Thanks a lot!

**Comment by mossmatters** [comment]
Great suggestion, and I have never written a progress bar before, so it was a good challenge! I've added one to the develop branch, it will be in the main branch at the next update. Sorry for the delay implementing it!
