### ISSUE TITLE
Issue with distribute_targets.py

### ISSUE THREAD

**Issue by Ptero64** [mossmatters/HybPiper#39]
Hello,

I am trying to run HybPiper on my data but I have error that I dont know how to fix. I was able to run the test-data without problem and also on a very small sample as a test too.
But now I need to run it on my data and if have error I haven't seen before. 

As target file I have the sequences of my coding mRNA from two species:
>GenusA-gene01
ATCGATCA
>GenusB-gene01
ATCGATCG

My fastq reads were trimmed and cleaned using TrimGalore. When I run the first script reads_first.py with -bwa it looks like the script fail at the step distribute_targets.py.
here is the error message:

raceback (most recent call last):
  File "/data/autoScratch/monthly/btx246/HybPiper/distribute_targets.py", line 93, in tailored_target_bwa
    protname = hitname[1]
IndexError: list index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/data/autoScratch/monthly/btx246/HybPiper/distribute_targets.py", line 189, in <module>
    if __name__=="__main__":main()
  File "/data/autoScratch/monthly/btx246/HybPiper/distribute_targets.py", line 184, in main
    besthits = tailored_target_bwa(args.bam,args.unpaired,args.exclude)
  File "/data/autoScratch/monthly/btx246/HybPiper/distribute_targets.py", line 95, in tailored_target_bwa
    raise IndexError("Gene name not found! FASTA headers should be formatted like this:\n >SpeciesName-GeneName\n")
IndexError: Gene name not found! FASTA headers should be formatted like this:
 >SpeciesName-GeneName

then
ERROR: Something went wrong distributing targets to gene directories.

Do you have an idea of what could be the problem?

I thank you in advance for the help.

Best regards

Nicolas
[error_reads_first.txt](https://github.com/mossmatters/HybPiper/files/2350138/error_reads_first.txt)

**Comment by thm52126** [comment]
@Ptero64 did you figure out this issue? I am getting a similar error.
