### ISSUE TITLE
ValueError: Sequence and quality captions differ

### ISSUE THREAD

**Issue by ryansfuller** [mossmatters/HybPiper#40]
Hello,
I am running into an error during my HybPiper runs on a Linux machine. 
Here is my input command to terminal:
python3 ~/HybPiper/reads_first.py -b Angiosperms353_targetSequences.fasta -r /scratch/Rhodo-reseq/data/R.rigidum/R.rigidum_R1.tmpfixed.fq.gz /scratch/Rhodo-reseq/data/R.rigidum/R.rigidum_R2.tmpfixed.fq.gz --prefix R.rigidum --bwa

The pipeline finishes the BWA alignment, creating a .bam file. However, when executing the distribute_reads_to_targets_bwa.py scripts it seems to fail upon calling QualityIO.py with the following error message:

Unique reads with hits: 220174
Traceback (most recent call last):
  File "/home/rfuller/HybPiper/distribute_reads_to_targets_bwa.py", line 111, in <module>
    if __name__ == "__main__":main()
  File "/home/rfuller/HybPiper/distribute_reads_to_targets_bwa.py", line 107, in main
    distribute_reads(readfiles,read_hit_dict,single=True)
  File "/home/rfuller/HybPiper/distribute_reads_to_targets_bwa.py", line 83, in distribute_reads
    for ID1_long, Seq1, Qual1 in iterator1:
  File "/usr/lib/python2.7/dist-packages/Bio/SeqIO/QualityIO.py", line 922, in FastqGeneralIterator
    raise ValueError("Sequence and quality captions differ.")
ValueError: Sequence and quality captions differ.
Command exited with non-zero status 1
313.88user 55.00system 6:27.88elapsed 95%CPU (0avgtext+0avgdata 281572maxresident)k
28689400inputs+0outputs (59major+132096minor)pagefaults 0swaps
ERROR: Something went wrong with distributing reads to gene directories.

Here is the first few lines of my .fq files with 150 paired-end Illumina reads:
@ST-E00167:450:HMN3NCCXY:5:1101:2838:1309 1:N:0
NTTTTGTTGTCTGAAGATGTATCCCATGAATTGAGTTTTATGAGAATGACCTTGATGCTGTCAAAACAAAAACAAAGAGAGTAAAATATACTCCCTCCGTCCCTAAATAAGTGTCCGGCGCGCAAAACTAGGCCTTACAAAAGAGGCATG
+
#AAAAFJJJJJJJJJJJJFJJJJJJJJJJFFJJJF<F<JJ-FJ7FJFJJJJJFAFFFFJJJFJJJJJJJJJJJJJJJFJJJ<JFJJJJJJJFJJFJJJJJJJJFFFFFFJJFAAFFFFJJJJJFJJJJJJJJF<<AJFJJJJJF<F77F
@ST-E00167:450:HMN3NCCXY:5:1101:2838:1309 1:N:0
NTTTTGTTGTCTGAAGATGTATCCCATGAATTGAGTTTTATGAGAATGACCTTGATGCTGTCAAAACAAAAACAAAGAGAGTAAAATATACTCCCTCCGTCCCTAAATAAGTGTCCGGCGCGCAAAACTAGGCCTTACAAAAGAGGCATG
+
#AAAAFJJJJJJJJJJJJFJJJJJJJJJJFFJJJF<F<JJFJ7FJFJJJJJFAFFFFJJJFJJJJJJJJJJJJJJJFJJJ<JFJJJJJJJFJJFJJJJJJJJFFFFFFJJFAAFFFFJJJJJFJJJJJJJJF<<AJFJJJJJF<F77F
@ST-E00167:450:HMN3NCCXY:5:1101:2899:1309 1:N:0
NGTTGGGTGTGGTGTTAGAATTATTGTTAGTTTTCCTCTCCAAGCACAGACACATATGTCTGTCAGTCTGTGTAGAGTATCTGCTACGCTATTGCTGTGTTGTTAGAGCAAGTTTATTAATGATAAGGTAAAAAAAGGCAAAATACCCTG
+
#A-AFAFF7AFFJFJJFJJAJJJJJJJJJJJJJJJJJJFJJJJFFFJF<<FFFFFA<---FJFFAFJJ<FFJF<<JJJ<<A<AA-<<A<<FJF-AFFA<AA<AJJJFFA-77<FFJF7FAFFA<JFFJ-AF<AJFJFJJA-<<JJFA

From what I have read, sequence and quality captions must match. But in .fq files, any string is optional after the '+' OR if there is any input here, it must match the sequence caption. I have not had any issues with these files when running in isolated BWA and Bowtie alignments and subsequent conversions to fastq files.

Any advice would be much appreciated. Thank you!

**Comment by finchnSNPs** [comment]
I'm having the same problem. Did you perform quality trimming on your sequence files? I didn't, but I have very high quality scores from fastQC. Could this have anything to do with read group assignments? I know read group assignments are required for bwa---->vcf with samtools and GATK.

**Comment by finchnSNPs** [comment]
This might be helpful. 
[](https://github.com/snayfach/MicrobeCensus/issues/4)

**Comment by V-Z** [comment]
I have same error. I run it as `python2 HybPiper/reads_first.py --bwa -r $SAMPLE.R{1,2}.fastq.gz -b $BAITFILE --cpu 12 --prefix $SAMPLE` and I get an error

    Traceback (most recent call last):
      File "/scratch/gunnera/job_11004449.arien-pro.ics.muni.cz/HybPiper/distribute_reads_to_targets_bwa.py", line 111, in <module>
        if __name__ == "__main__":main()
      File "/scratch/gunnera/job_11004449.arien-pro.ics.muni.cz/HybPiper/distribute_reads_to_targets_bwa.py", line 107, in main
        distribute_reads(readfiles,read_hit_dict,single=True)
      File "/scratch/gunnera/job_11004449.arien-pro.ics.muni.cz/HybPiper/distribute_reads_to_targets_bwa.py", line 83, in distribute_reads
        for ID1_long, Seq1, Qual1 in iterator1:
      File "/software/python27-modules/software/python-2.7.6/gcc/lib/python2.7/site-packages/Bio/SeqIO/QualityIO.py", line 920, in FastqGeneralIterator
        raise ValueError("Sequence and quality captions differ.")
    ValueError: Sequence and quality captions differ.

My FASTQ looks like

    @NS500595:90:HKTV2AFXX:3:21405:23894:13521/1
    AAAAAAAAAAAAAATTACTTGGGACCATTGGAGTGATCATCTTGATCTATAAGCTTAACGGTGAACTCCTTCCACACAAAAGGAAGTTCACCAGCTGTGTACAAACTCTTTCTGCCATCATAAGCAGGTA
    +
    AAAAAEEEEEEE66EEA//AEEEAEEAEEEA6EAE/EE//EEAEAAA6EEE/EEE6EE<//EE/E//AEE<E//6AAEEEAEAEA/E/E/E/EE6E/E</EAE<EE///EE/EAEEA/AEAE/EE<///E
    @NS500595:90:HKTV2AFXX:1:11301:13733:17090/1
    AAAAAAAAAAAAAATTCTAATTTTTTAATACATACCATC
    +
    AAAAAEEEEEEE<EEE//AEAEEEEEA/E/EAE/EE//A
    @NS500595:90:HKTV2AFXX:3:21611:19494:2466/1
    AAAAAAAAAAAAACAGACACATCAACCCGTAGAGATTAGAGAGAGGGCGTGTTTATAAATTACAGATCTAATCAGATCAAGATTGAGCTCTTCAGGCTTC
    +
    AAAAAEEEEE66/EAAAE/AA/EEA/E/EE/E/EEEEEE///EEE/EEEEEE/EE/EE/EEEEEEE/AEE///A<E//EEAEAE//EEEAE/</EE/E/6
    @NS500595:90:HKTV2AFXX:4:21408:6179:18370/1
    AAAAAAAAAAAAACTCTGTTTTAAAAAAATTAAGCATATATTTTTAA
    +
    AA/6AEEEEEEAA//AAAEEEA/EEE6EE6AEEEEE/E</<AEEEEA
    @NS500595:90:HKTV2AFXX:2:11306:7354:4806/1
    AAAAAAAAAAAACAAACACTTTTAGTTTTTCGAAATATTCTTTTCGGTGATGAAAAACATGAAACAATTACCCGTTGTTGGTTTTTAATATGATTTGTTTTAGGTCTGTTAAAGTTTTGAATTAACATAATTCTGATATTTTCAATTGGAT
    +
    AAAAAEEEEEEEEEE6E/E/EEE6EEEEEEE/EEEEEEE/AEEEEAEAEE/EAEE6EAE/EEEEAE/E//EE//EEEE/EA/EAEEAEEAEEEEE//AEEEEEAAAEE/EEEEEEEE<AEAEEEEEEEEAEE<E/A//EEEE/E/AE<AAE
    @NS500595:90:HKTV2AFXX:1:21306:19185:18801/1
    AAAAAAAAAAAAGATTATTTCGGCACCGTAAATTACTTCTCGATTTTTTTTTCATTTTGCATGTCTTTTTATCTAAAGTACT
    +
    AAAAAEEEEEE6E6EEEEEEEEEEAEEEEEE/EEE/AEAEEEEEEEEEEEE//<EEEEEEE/EAEEEEEAAEE/EEE</E/E
    @NS500595:90:HKTV2AFXX:1:11210:25857:7344/1
    AAAAAAAAAAAAGCCCAGCATTGTTACTTACAGAGCGGAAATACTCGACAAACCGTGGCGCGTTGAAAACAA
    +
    AAAAAEEEEE6E/EEA/EA6EEAEEAAEAAE6A/E/EAEE/E6E//E/EA//EAE/EAE//E/EE/A6/E/6
    @NS500595:90:HKTV2AFXX:2:11209:10053:12172/1
    AAAAAAAAAAAAGTGTCTGTCTTAGTGTGGTGGATAACTGGGTGGGGTGACAGGTGTATCCGCCCCACACCTGAAGAGCTGGAGAATTTTGGTACTCCGGACTTCACTATTTATAACGCTGGACAGTTCCCGGGTAACCGTTAT
    +
    AAAAAEEEEEE6EEE6AAA//EEEE/EEEA/EEAEEE//EEE6EEEEEE/A/E/EEE//EEEAEEEAE/EE/EEEE/E//EE/EE/EEEEEEE/E/EEEE/EE/E/EE/EEE/EE/EEEAEE/E/EE/EEEE/EAE/EAE///E
    @NS500595:90:HKTV2AFXX:1:11106:17831:3562/1
    AAAAAAAAAAAATTACTTGGGACCATTGGAGTGATCATCTTGATCTATAAGCTTAACGGTGAACTCCTTCCACACAAAAGGAAGT
    +
    AAAAA/EEEEE6EEE/EEEE66EAAEEA666EEEEA/E/EEEEE/EEEEE6/EAE/EE<E//EEEE/AAEAA/A<EEEA6EE66E
    @NS500595:90:HKTV2AFXX:2:21301:7074:3403/1
    AAAAAAAAAAACTCACCGGCCCAAAAAGGAGGCACTCCAATTTATAAAATG
    +
    AAAAAEEEAEAA/E/EEAEE/</EEE/EE/EEE6EE/E//EE//E6EEE/A
    @NS500595:90:HKTV2AFXX:2:11209:12079:6487/1
    AAAAAAAAAAACTGATTCATAGTGCATACCACTTTGTGTTGACAGAGCAATGCGATCTCTTAAGATAGCAAGCTCAGGAGACAATTC
    +
    AAAAAEEEEE6E/EAEEEAA/A/AEEE/AE//EEE//EE/E/EE/6EEE/EEA6E/E//EEEE66E6EAE/EE/A/E/EA/EEEE/E

which looks fine to me. I'm trying to find out what's wrong...

**Comment by V-Z** [comment]
I forget to report my solution: uncompress the sequence. ;-) I use to keep the sequences compressed by bzip2, which usually work, but here BioPython isn't complaining about the compression itself, but just throws weird error...

**Comment by full6186** [comment]
Sorry for the late reply on all of this. Seems many messages from GitHub were being filtered to my junk mail. Go figure. As V-Z commented above, my solution was to decompress the sequence files. It's kind of a pain, but it worked for me after that. I tested it a few times and am certain this is where the error is stemming from.

**Comment by mossmatters** [comment]
Will be addressed in HybPiper 2.0
