### ISSUE TITLE
Number of files produced

### ISSUE THREAD

**Issue by Jasmine0198** [mossmatters/HybPiper#44]
Hello,
I am currently processing reads using HybPiper and have found that the analysis produces around 50,000 files or directories per sample analysed. I have around 20 samples to analyse and an inode limit of 300,000, which means that I can't analyse all the samples at the same time. Are there files produced that I might not need downstream that I can delete? If so could you recommend which? Many thanks,
Jasmine

**Comment by mossmatters** [comment]
Jasmine,

If you use the `cleanup.py` script after running `reads_first.py`, a large number of intermediate files will be deleted. Most of the files are associated with the Spades assembly and are not needed for any downstream analysis. Hopefully that will keep the number of files to a minimum. Let me know if you need any further assistance!

**Comment by Jasmine0198** [comment]
Thanks so much! Sorry, I should have seen that.
