### ISSUE TITLE
Hybpiper "sticking"

### ISSUE THREAD

**Issue by tomwells-oxf** [mossmatters/HybPiper#46]
Hi, I appear to be having an issue where for some of my samples the analysis gets stuck on a particular locus and the ETA just keeps climbing (please see below the status below - the previous locus has finished fine, but this one is still running and doesn't look like finishing). One sample was like that for almost 4 days until I cancelled it and continued to the next one. Other samples seem to work fine.
I'm aware that the sequence data might not be very good for some samples. Could this be causing the problems? Thanks for your help.
All the best,
Tom

ETA: 0s Left: 4 AVG: 0.01s  local:4/339/100%/0.0s There were 471 exonerate hits for Solyc11g069150.1.1_1/Solyc11g069150.1.1_1_baits.fasta.
I_lacunosa-Solyc11g069150.1.1_1Writing amino acid sequence, length: 130
ETA: 0s Left: 3 AVG: 0.01s  local:3/340/100%/0.0s There were 693 exonerate hits for Solyc11g010890.1.1_1/Solyc11g010890.1.1_1_baits.fasta.
I_lacunosa-Solyc11g010890.1.1_1Writing amino acid sequence, length: 211
ETA: 0s Left: 2 AVG: 0.04s  local:2/341/100%/0.0s There were 4766 exonerate hits for Solyc07g063040.2.1_1/Solyc07g063040.2.1_1_baits.fasta.
I_lacunosa-Solyc07g063040.2.1_1Writing amino acid sequence, length: 53
ETA: 71s Left: 1 AVG: 71.53s  local:1/342/100%/71.5s

**Comment by mossmatters** [comment]
Hello -- yes, highly repetitive or extremely short sequences could result in issues with HybPiper getting stuck at the Spades or Exonerate stages.

If you call `reads_first.py` with the argument `--timeout 1000` it will pass that to `parallel` when it is running either `spades.py` or `exonerate_hits.py`. The number is a percentage compared to the average time needed for the other jobs to finish. In your example, the average is reported as 0.04 seconds, and so `--timeout 1000` would kill any job that is taking more than 4 seconds. This should allow HybPiper to exit gracefully.

**Comment by tomwells-oxf** [comment]
Hi Matt,
Thank you so much, that is really helpful.
I have a second query as it happens for if you have a minute.
I'm trying to use gatk's haplotype caller on each locus for another dataset.
I've been buildng sam files by mapping the interleaved.fasta file to the relevant target locus, converting those to bam files and trying to use them as the input for haplotype caller.
Unfotunately gatk seems to want quality scores for the reads, which don't seem to be retained in the interleave.fasta file. Is there a way to retain the quality scores when the original mapping is being done?
The long-winded workaround I am trying at the minute is to use the read names from the interleave file to grep the original fastq file, then map those (with their quality scores) to the reference locus. That way at least I'm not redoing the whole thing, but it still doesn't feel like the best way to do it..
Any help greatly appreciated!
Thanks again.
All the best,
Tom

________________________________
