### ISSUE TITLE
/bin/sh: 1: time: not found

### ISSUE THREAD

**Issue by EugenioVE** [mossmatters/HybPiper#50]
Dear Matt and all,
I am getting this error after setting HybPiper in a new server. I haven't been able to get around it or to find any reports about it... any help or idea would be really helpful:
Thank a lot in advance,
Eugenio Valderrama

(base) ev243@debian:~$ reads_first.py --check-depend
HybPiper was called with these arguments:
/home/ev243/HybPiper/reads_first.py --check-depend

blastx found at /home/ev243/ncbi-blast-2.10.0+/bin/blastx
exonerate found at /home/ev243/exonerate-2.2.0-x86_64/bin/exonerate
parallel found at /home/ev243/miniconda3/bin/parallel
makeblastdb found at /home/ev243/ncbi-blast-2.10.0+/bin/makeblastdb
spades.py found at /home/ev243/SPAdes-3.14.0-Linux/bin/spades.py
bwa found at /home/ev243/miniconda3/bin/bwa
samtools found at /home/ev243/miniconda3/bin/samtools
Package Bio successfully loaded!
Everything looks good!
(base) ev243@debian:~$ 
(base) ev243@debian:~$ 
(base) ev243@debian:~$ reads_first.py -b /home/ev243/HybPiper/test_dataset/test_targets.fasta -r /home/ev243/HybPiper/test_dataset/NZ281_R*_test.fastq --prefix NZ281 --bwa
HybPiper was called with these arguments:
/home/ev243/HybPiper/reads_first.py -b /home/ev243/HybPiper/test_dataset/test_targets.fasta -r /home/ev243/HybPiper/test_dataset/NZ281_R1_test.fastq /home/ev243/HybPiper/test_dataset/NZ281_R2_test.fastq --prefix NZ281 --bwa

Making nucleotide bwa index in current directory.
[CMD]: bwa index test_targets.fasta
[bwa_index] Pack FASTA... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.02 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.01 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index test_targets.fasta
[main] Real time: 0.031 sec; CPU: 0.031 sec
[CMD]: time bwa mem -t 80 test_targets.fasta /home/ev243/HybPiper/test_dataset/NZ281_R1_test.fastq /home/ev243/HybPiper/test_dataset/NZ281_R2_test.fastq  | samtools view -h -b -S - >  NZ281.bam
/bin/sh: 1: time: not found
[CMD] time python /data/home/ev243/HybPiper/distribute_reads_to_targets_bwa.py NZ281.bam /home/ev243/HybPiper/test_dataset/NZ281_R1_test.fastq /home/ev243/HybPiper/test_dataset/NZ281_R2_test.fastq

/bin/sh: 1: time: not found
ERROR: Something went wrong with distributing reads to gene directories.
(base) ev243@debian:~$

**Comment by mossmatters** [comment]
This is a new one for me too! It seems like maybe the `time` command doesn't work with `sh`: https://superuser.com/questions/418325/sh-time-command-not-found

I wrote the commands for HybPiper assuming people would be using `bash` rather than `sh` so I am not sure if that is the issue. I wonder if you enter a `bash` shell and then run HybPiper, would it work then?

Alternatively, maybe because it is a new system not all of the tools got installed? You could try `apt-get install time` based on this: https://askubuntu.com/questions/86193/command-not-found-when-trying-to-set-a-format-for-the-time-command/86196#86196

**Comment by EugenioVE** [comment]
Thanks Matt... I am using a `bash` shell. I don't understand why the `/bin/sh` in the error... however, will ask the admin to try `apt-get install time` and let you know how it goes

**Comment by EugenioVE** [comment]
All OK after installing `time`... Thanks a lot!
