### ISSUE TITLE
spades. py --cov-cutoff 8, is it possible to change this

### ISSUE THREAD

**Issue by Deco313** [mossmatters/HybPiper#52]
So I am comparing Ultra Conserved Element assemblies with HybPiper and PhylUCE. For this I want the spades  cov-cut off to be 2 instead of 8. However when I manually change 
spades_cmd_list = ["spades.py --only-assembler --threads 1 --cov-cutoff " ,str(cov-cutoff)]
to
spades_cmd_list = ["spades.py --only-assembler --threads 1 --cov-cutoff 2" ,str(cov-cutoff)]

It throws errors further down. 

Traceback (most recent call last):
  File "/ichec/home/users/deco313/HybPiper/spades_runner.py", line 189, in <module>
    if __name__ == "__main__":main()
  File "/ichec/home/users/deco313/HybPiper/spades_runner.py", line 183, in main
    spades_failed,spades_duds = rerun_spades("failed_spades.txt",cov_cutoff=args.cov_cutoff,paired=is_paired,cpu=args.cpu)
  File "/ichec/home/users/deco313/HybPiper/spades_runner.py", line 97, in rerun_spades
    all_kmers = [int(x[1:]) for x in os.listdir(os.path.join(gene,"{}_spades".format(gene))) if x.startswith("K")]
OSError: [Errno 2] No such file or directory: '6134_p10/6134_p10_spades'
WARNING: Something went wrong with the assemblies! Check for failed assemblies and re-run!
ERROR: No genes had assembled contigs! Exiting!

How do I change this?

Thank you.

**Comment by mossmatters** [comment]
Hi, sorry for the delay! My first question is whether you are re-running the cov_cutoff=2 in the same directory as cov_cutoff=8? If so HybPiper may have not overwritten files appropriately, so it's looking for assemblies that don't exist. You can test this by supplying a different --prefix for the new run. Let me know if that fixes it, if not I can dive into it deeper!

**Comment by Deco313** [comment]
No problem turns out I should have manually set --cov_cutoff 2 at the reads_first.py arguments. I am now running through the pipeline. I think also my Target file was in the shape of my bait file so I don't think it was aligning correctly anyway
