### ISSUE TITLE
problem with SpAdes

### ISSUE THREAD

**Issue by edgagnon** [mossmatters/HybPiper#54]
Hi, I just wanted to signal a problem I had with the SpaDES assembly step:
I was getting an error message from the SpaDEs log that was suggesting that my fasta files were empty. When launching read_first.py, I specified the --unpaired argument. For some of my genes, this file was empty, and was thus causing an error and resulting in the gene being completely skipped in the analysis, even though there were sequences in the .interleave file

Is there a way to ask HybPiper to use only the unpaired.fasta file if it is not empty?

**Comment by chrisjackson-pellicle** [comment]
Hi @edgagnon,

Thanks for raising this issue - it made me realise that this bug had crept through in to HybPiper version 2.0.0 as well! I'm not sure if this will still be relevant to your research, but I've just pushed version 2.0.1 which should resolve it. 

Cheers,

Chris
