### ISSUE TITLE
spades not running on all genes for some samples

### ISSUE THREAD

**Issue by willyard** [mossmatters/HybPiper#58]
Hello Matt,
The HybPiper reads_first.py script is aborting after SPAdes for most of our samples. I used this lovely script successfully for a previous dataset on a previous server. I am stumped at the moment for the current dataset. Oddly, two of our samples have worked fine, yielding genes_with_seqs.txt. 
Because there was a SPAdes warning to clear files, we deleted all HybPiper folders for a failed sample and re-ran. Tracing the spades.log for the rerun of the failed sample, it looks like it is only running for one (or maybe two) of our 1000 genes, and these are not the first or last in the gene list. The SPAdes log file at the top shows an output directory that includes one gene that SPAdes ran successfully for. Nonetheless, the spades.log is really in the directory for this sample, as expected. At the end of the spades.log, that it says that it ended with warnings, but that message gives a directory inside a different gene 
Any suggestions for how to debug? We are running samples one at a time, by the way.
Thanks,
--Ann

**Comment by mossmatters** [comment]
Ann,

The first thing that comes to mind is whether you are using scratch space local to the compute node on the new sever- you could be having issues with files not synching between the compute node and the storage node. As a result Spades would then quit because its intermediate files cannot be found.

If that's not it, the next thing I would suggest is running `spades_runner.py` separately for a sample with a successful read mapping stage. You will be able to track the progress from Spades a bit better then. Let me know how it works out!

**Comment by willyard** [comment]
Hello Matt,

Thanks for taking time to answer this directly. We seem to have solved the problem by switching to PuTTY in order to use the KeepAlive feature. I don’t know why plain vanilla SSH worked for me on my last project and not this one, but there are many computer mysteries that biologists will never have the attention span to figure out. Get it to work, then move on to something biologically interesting. That’s my motto. Thankful that others are helping.

In any case, I hope that you are doing well in these trying times and I appreciate help from you and from my colleague Jeff Wilson (cc’d here).

Cheers,
--Ann

Ann Willyard
Associate Professor, Retired
Hendrix College
willyard@hendrix.edu

**Comment by willyard** [comment]
Hello Matt,

I am now positive that Ann has been losing her ssh session to the server due to inactivity which would orphan the running processes.  Consequently, the orphaned process would eventually die and not the subsequent processes.  Everything seems to be fine now that we’re able to keep Ann’s ssh session active.  We could have run the processes as background processes, but this seemed to be the most straight forward for Ann.

The HybPiper scripts and data are stored on AWS EFS, Elastic File Storage.  We are also working directly on the  EFS space, as in the current directory is within the EFS directory structure.  Therefore, I don’t think we’re using any scratch space, swap or anything like it directly.

Thank you for your help.

- Jeff

=============================
Jeff Wilson
Botanical Tech, Computer Coordinator
W. J. Beal Botanical Garden and Campus Arboretum
207 Olds Hall
408 West Circle Dr
Michigan State University
East Lansing, MI  48824
Phone: 517.884.0761 | Fax: 517.432.1090





From: Willyard, Ann <Willyard@hendrix.edu>
Sent: Wednesday, December 09, 2020 1:22 PM
To: mossmatters/HybPiper <reply@reply.github.com>
Cc: Wilson, Jeffrey <wilson23@msu.edu>; Willyard, Ann <Willyard@hendrix.edu>
Subject: RE: [mossmatters/HybPiper] spades not running on all genes for some samples (#58)

Hello Matt,

Thanks for taking time to answer this directly. We seem to have solved the problem by switching to PuTTY in order to use the KeepAlive feature. I don’t know why plain vanilla SSH worked for me on my last project and not this one, but there are many computer mysteries that biologists will never have the attention span to figure out. Get it to work, then move on to something biologically interesting. That’s my motto. Thankful that others are helping.

In any case, I hope that you are doing well in these trying times and I appreciate help from you and from my colleague Jeff Wilson (cc’d here).

Cheers,
--Ann

Ann Willyard
Associate Professor, Retired
Hendrix College
willyard@hendrix.edu<mailto:willyard@hendrix.edu>
