### ISSUE TITLE
CPU and memory consumption

### ISSUE THREAD

**Issue by mdgn15** [mossmatters/HybPiper#63]
Hello,

Thank you for this nice and very useful pipeline. I have a problem regarding the CPU and memory consumption. Whenever I submit a job in my grid server, the jobs are killed because of mainly CPU (and potentially memory) limit is violated. I realize the pipeline as default uses the maximum number of CPU's in the whole grid and this is the main cause. I managed to limit the consumption of spades although it still somehow goes over the limit. Also  exonerate seems to cause this (I am not totally sure) because even the analysis makes it through spades it is getting killed in this step, but I couldn't find an option for this in the scripts. Do you have some general comment about this? Also maybe a future request would be adding a main cpu/memory option to reads_first.py.

Thank you,

Mert

**Comment by mossmatters** [comment]
Mert,

`reads_first.py` has a `--cpu` flag that you can use to limit the CPU usage, for example: `--cpu 24`. 

Each of the downstream steps (BWA, Spades, Exonerate) is supposed to use this number of threads -- in the case of BWA it is multithreading on (for example) 24 threads.  For Spades and Exonerate, it is running each of those single-threaded (e.g. `spades.py --threads 1`), but Hybpiper would run 24 genes at once using`parallel`.

If you're using the `--cpu` flag and still getting those issues, I will need to check that one or more of the steps is not obeying that command or if an update from one of the dependencies has changed things. Let me know!

~Matt

**Comment by mdgn15** [comment]
Hello Matt,

Yes, its my bad, I realized the option for cpu just after writing the message. I was just following the tutorial and didn't think about checking - help. There are no problems its working perfectly:). 

Thank you again!
