### ISSUE TITLE
How is the FAA document translated

### ISSUE THREAD

**Issue by yltuang** [mossmatters/HybPiper#66]
Hello:
       I want to analysis for selection (Ka/Ks), which is based on the codons dataset,so the order of bases is very demanding.However,my ref_seq is not start with AUG( initiation codon), so I dont know how the FAA document is got,is there error of frame-shift mutation,may I use it for the analysis for selection?

Best wishes!
Thanks!

**Comment by mossmatters** [comment]
The FAA file is a direct translation of the FNA file as an output of `exonerate`. It is supposed to be in frame, but if the start site is missing, you may have not recovered the beginning of the coding region in your sample. 

Frameshift mutations are possible, or errors with detecting the open reading frame at intron/exon boundaries. I would recommend taking the FNA sequences from each sample and using MACSE (https://bioweb.supagro.inra.fr/macse/) to generate an in-frame multiple sequence alignment. MACSE can handle frameshift mutations.

**Comment by yltuang** [comment]
Thank you very much!

**Comment by yltuang** [comment]
> FAA 文件是 FNA 文件的直接翻译，作为`exonerate`. 它应该在框架内，但如果缺少起始位点，则您可能没有恢复样本中编码区域的开头。
> 
> 移码突变是可能的，或者在内含子/外显子边界检测开放阅读框时出错。我建议从每个样本中获取 FNA 序列并使用 MACSE ( https://bioweb.supagro.inra.fr/macse/ ) 生成帧内多序列比对。MACSE 可以处理移码突变。

 You are so nich，this helped me a lot！Thank you very much!

**Comment by yltuang** [comment]
> FAA 文件是 FNA 文件的直接翻译，作为`exonerate`. 它应该在框架内，但如果缺少起始位点，则您可能没有恢复样本中编码区域的开头。
> 
> 移码突变是可能的，或者在内含子/外显子边界检测开放阅读框时出错。我建议从每个样本中获取 FNA 序列并使用 MACSE ( https://bioweb.supagro.inra.fr/macse/ ) 生成帧内多序列比对。MACSE 可以处理移码突变。

You are so nich,help me a lot,thank you very much!

**Comment by yltuang** [comment]
> FAA 文件是 FNA 文件的直接翻译，作为`exonerate`. 它应该在框架内，但如果缺少起始位点，则您可能没有恢复样本中编码区域的开头。
> 
> 移码突变是可能的，或者在内含子/外显子边界检测开放阅读框时出错。我建议从每个样本中获取 FNA 序列并使用 MACSE ( https://bioweb.supagro.inra.fr/macse/ ) 生成帧内多序列比对。MACSE 可以处理移码突变。

You are so nice,help me a lot,thank you very much!
