### ISSUE TITLE
Issue with BWA

### ISSUE THREAD

**Issue by sagesteppe** [mossmatters/HybPiper#69]
I have been having an issue with processing my data (MiSeq paired end reads) using HybPiper. I have moved this directory over into the location  where HybPiper was installed via a Conda environment on Ubuntu 20.04 (I see some others had Conda problems but I do not think I have any).

Traceback (most recent call last):
  File "/home/steppe/HybPiper/Rosales/../reads_first.py", line 769, in <module>
    if __name__ == "__main__":main()
  File "/home/steppe/HybPiper/Rosales/../reads_first.py", line 681, in main
    bamfile = bwa(readfiles,baitfile,basename,cpu=args.cpu)
  File "/home/steppe/HybPiper/Rosales/../reads_first.py", line 590, in bwa
    full_command = " ".join(bwa_commands)

I am using NewTargets for generating target sequences - but am quite confident these are correct. I am quite at a loss for what is wrong; seems it is looking for a module. Wondering if there are any ideas here?

**Comment by mossmatters** [comment]
Hi, sorry I am late in seeing this. If you are still having issues, can you post the full `reads_first.py` command you used, and the full error?

**Comment by sagesteppe** [comment]
Hi Matt,

No problem, happy for any help you can give. I just re-ran the example data set again without any problems, and looked at the NewTargets file (called filtered_target_file.fasta) and my namelist.txt and both appear valid. 

(metagenomics) steppe@steppe-steppe:~/HybPiper/Rosales$ while read name; 
> do ../reads_first.py -b filtered_target_file.fasta -r $name*.fastq --prefix $name --bwa;
> done < namelist.txt
HybPiper was called with these arguments:
../reads_first.py -b filtered_target_file.fasta -r 14_a_S59_P_R1.fastq 14_a_S59_R2_P.fastq 14_a_S59_R2_U.fastq 14_a_S59_U_R1.fastq --prefix 14_a_S59 --bwa

Making nucleotide bwa index in current directory.
[CMD]: bwa index filtered_target_file.fasta
[bwa_index] Pack FASTA... 0.02 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.90 seconds elapse.
[bwa_index] Update BWT... 0.02 sec
[bwa_index] Pack forward-only FASTA... 0.02 sec
[bwa_index] Construct SA from BWT and Occ... 0.34 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index filtered_target_file.fasta
[main] Real time: 1.324 sec; CPU: 1.299 sec
Traceback (most recent call last):
  File "/home/steppe/HybPiper/Rosales/../reads_first.py", line 769, in <module>
    if __name__ == "__main__":main()
  File "/home/steppe/HybPiper/Rosales/../reads_first.py", line 681, in main
    bamfile = bwa(readfiles,baitfile,basename,cpu=args.cpu)
  File "/home/steppe/HybPiper/Rosales/../reads_first.py", line 590, in bwa
    full_command = " ".join(bwa_commands)
TypeError: sequence item 4: expected str instance, list found
HybPiper was called with these arguments:
../reads_first.py -b filtered_target_file.fasta -r 14_b_S63_P_R1.fastq 14_b_S63_R2_P.fastq 14_b_S63_R2_U.fastq 14_b_S63_U_R1.fastq --prefix 14_b_S63 --bwa


Let me know if you are interested and want these data etc., I am happy to compress and share the materials.

**Comment by chrisjackson-pellicle** [comment]
Hi @sagesteppe,

This is happening because HybPiper expects a maximum of two read files (R1 and R2) when using the `-r` parameter, whereas you have provided four files. You can `cat` your two unpaired readfiles together and provide them to HybPiper using the `--unpaired` parameter. If you provide more than two files using the `-r` parameter to HybPiper 2.0 it exits with a slightly more helpful error message (i.e. `Can not determine whether <read files provided> is single-end, paired-end or unpaired!`), but I'll insert an explicit check for this earlier in the pipeline with an explicit error message.

Cheers,

Chris

**Comment by sagesteppe** [comment]
Thanks Chris, 

I am traveling now but will try this out as soon as I return!!

Thanks again!

**Comment by chrisjackson-pellicle** [comment]
Good to hear, and thanks for letting me know!
