### ISSUE TITLE
hybpiper cannot locate python packages.

### ISSUE THREAD

**Issue by sun-jiao** [mossmatters/HybPiper#75]
installed using conda following the instruction in wiki.
 
Biopython was built from source code and installed:
![image](https://user-images.githubusercontent.com/14086980/170694952-6642ec5d-375b-48c3-96d1-f9c86846d268.png)

but hybpiper cannot locate the following python packages.
![image](https://user-images.githubusercontent.com/14086980/170694664-83c8d4e4-900a-4f89-bfaf-b3146e1ac725.png)

**Comment by chrisjackson-pellicle** [comment]
Hi @sun-jiao,

That's odd. It looks like HybPiper might be using a Python installation that's different to the one present in your `hybpiper` conda environment. 

Firstly, the turn-it-off-and-turn-it-on-again approach: does deactivating and reactivating the `hybpiper` conda environment have any effect?

Could you post the output of:

1) `conda --version`

2) `cat $(which hybpiper)` (when in the conda `hybpiper` environment)

3) `echo $PATH` (when in the conda `hybpiper` environment)

For command 2, you should see the location of the Python installed in the `hybpiper` environment. For example, on my machine I get:

```
cat $(which hybpiper)
#!/bin/sh
'''exec' /home/cjackson/.conda/envs/hybpiper/bin/python "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys
from hybpiper.assemble import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
``` 

The location of this Python installation should also appear in your `$PATH` before any other Python installation on your machine. On my machine:

```
echo $PATH
/home/cjackson/.conda/envs/hybpiper/bin:/home/cjackson/.local/bin:/home/cjackson/bin:/usr/local/go/bin:/sbin:/home/cjackson/.local/bin:/home/cjackson/bin:/usr/local/go/bin:/sbin:/opt/miniconda3/miniconda3/condabin:/shared/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/cjackson/go/bin:/shared/bin:/home/cjackson/go/bin
```

Also, Biopython 1.80 is installed along with HybPiper when you install via conda, so no need for the manual installation. Where did your `biopython-1.80.dev0-etc` wheel come from?

Cheers,

Chris

**Comment by sun-jiao** [comment]
thanks @chrisjackson-pellicle , I'll try it and tell you whether it works. 

I build bio python from source code on my own.

**Comment by chrisjackson-pellicle** [comment]
@sun-jiao  - let's hope we can fix your issue, but it looks like this is an ongoing problem for some people, see https://github.com/conda/conda/issues/9392

As noted in the issue thread, try deactivating your conda `base` environment too before activating the `hybpiper` environment...

**Comment by sun-jiao** [comment]
@chrisjackson-pellicle I fixed the problem by completely removing python and conda and reinstalling them. Thanks for your help.

**Comment by chrisjackson-pellicle** [comment]
Great - glad it's working!
