### ISSUE TITLE
spades - DEBUG - Deleting SPAdes assembly folder for gene gene002.

### ISSUE THREAD

**Issue by hmqmuyang** [mossmatters/HybPiper#76]
dear author
When I run the test data, I get this error.
How to solve this？
The attachment is the log file，
thank you very much！
[EG30_hybpiper_assemble_2022-06-05-00_02_52.log](https://github.com/mossmatters/HybPiper/files/8838247/EG30_hybpiper_assemble_2022-06-05-00_02_52.log)

**Comment by chrisjackson-pellicle** [comment]
Hi @hmqmuyang ,

The message `spades - DEBUG - Deleting SPAdes assembly folder for gene`... is a standard debug message, so it's nothing to worry about.

However, it looks like something's going wrong at the SPAdes assembly step. From your log file I see you're running sample `EG30` from the test dataset. For this sample, all SPAdes initial assemblies should be successful, i.e. the lines in your logfile:

```
> 2022-06-05 00:06:03,006 - spades_runner.py - hybpiper.assemble.hybpiper.spades_runner - spades_initial - INFO - [WARNING]: One or more genes had an error with SPAdes assembly. This may be due to low coverage.
> 2022-06-05 00:06:03,049 - spades_runner.py - hybpiper.assemble.hybpiper.spades_runner - spades_initial - INFO - [WARNING]: Total number of genes with failed initial SPAdes run: 13. Gene names can be found in the sample log file.
> 2022-06-05 00:06:03,049 - spades_runner.py - hybpiper.assemble.hybpiper.spades_runner - spades_initial - DEBUG - gene079 gene002 gene111 gene006 gene001 gene030 gene074 gene461 gene293 gene012 gene026 gene298 gene660
```

Should read e.g.:

```
2022-06-06 10:43:59,148 - spades_runner.py - hybpiper.assemble.hybpiper.spades_runner - spades_initial - INFO - [WARNING]: Total number of genes with failed initial SPAdes run: 0. Gene names can be found in the sample log file.
```

Could you send me the `spades.log` file that should be in your `EG30` sample directory?

Cheers,

Chris

**Comment by hmqmuyang** [comment]
Hi, @chrisjackson-pellicle  
[spades.log](https://github.com/mossmatters/HybPiper/files/8849932/spades.log)

Thank you very much for your reply.
I uploaded the file，
To be clear, my system is CentOS 6.8 and can't seem to run spades1.5.
I tried to install hybpiper1.3, and use spades1.3, it can run normally.
Can I also use spades1.3 in hybpiper2.0?

All the best
mengqi

**Comment by chrisjackson-pellicle** [comment]
Hi @hmqmuyang 

Ah, that'll be it!

Yes, HybPiper 2 should run fine with SPAdes version 3.13. I guess you have a couple of options:

1) Install all dependencies manually (including biopython 1.80) and install HybPiper manually.
2) Try creating a new hybpiper conda environment from the attached `hybpiper2.yml` file:
  -   Unzip the  `hybpiper2.yml.gz` file (github doesn't support upload of plain `*.yml` files here)
  -  `conda env create --file hybpiper2.yml`
  -  `conda activate hybpiper`

The second option should install most of the dependencies (including SPAdes version 3.13), but you'll still need to install HybPiper and Biopython manually (as described [here](https://github.com/mossmatters/HybPiper/wiki/Installation#2----manual-installation-of-pipeline-and-dependencies) and [here](https://github.com/mossmatters/HybPiper#note)) within this environment.

Let me know how you go!

[hybpiper2.yml.gz](https://github.com/mossmatters/HybPiper/files/8857067/hybpiper2.yml.gz)

**Comment by chrisjackson-pellicle** [comment]
Hi @hmqmuyang,

I don't quite follow what you mean by:

> The prompt is the problem of dependent GLIBC2.14 and 2.17

Given you're happy to continue using HybPiper 1.3, I'll close this issue now. If you'd like to continue troubleshooting please feel free to re-open it, and provide full details regarding the approaches you've tried and the error messages you've received.

Cheers,

Chris
