### ISSUE TITLE
Fail to call Biopython 1.8

### ISSUE THREAD

**Issue by hyyuu** [mossmatters/HybPiper#78]
Hello , thank you for this great software.

Hybpiper was able to run smoothly , but it starts to return a fatal error.

`HybPiper required Biopython version 1.80 or above. You are using version 1.79. Please update your Biopython for the Python installation used to run HybPiper!`

I check Biopython1.8 is installed.  And I try to create a new hybpiper env to install it all over again, but it returns the same message.
How can I fix it ?
Thank you for your help :)

**Comment by chrisjackson-pellicle** [comment]
Hi @hyyuu,

Could you describe your exact installation process, please, including how you checked that Biopython 1.80 is installed?

A failure to find required Python modules/libraries when installing via conda can often be caused by the conda environment using a Python installation that's different to the one installed in the given environment (see my answer [here](https://github.com/mossmatters/HybPiper/issues/75#issuecomment-1140150259)). 

However, this might not be the case in your scenario. One of the first things HybPiper does when it runs is to try to import any required Python modules/libraries, and it exits with an error message if one or more can't be found. One of the modules checked is Biopython. The check for the Biopython version happens *after* this initial import check.

So, from what I can see, you're running HybPiper in an environment that has all the Python modules/libraries required by HybPiper (i.e. this list [here](https://github.com/mossmatters/HybPiper/wiki/Installation#dependencies)), but somehow you have Biopython 1.79 installed rather than 1.80. The conda install of HybPiper does not install BioPython 1.79 - did you install this yourself?

One solution might be to simply install Biopython version 1.80 manually, as described [here](https://github.com/mossmatters/HybPiper#note). It's not ideal to mix pip and conda, but if you're doing this in a HybPiper-specific environment it should be fine.

Cheers,

Chris

**Comment by hyyuu** [comment]
Hello @chrisjackson-pellicle , Thank you for your prompt response ! 

I strictly followed your installation instruction. It ran smoothly , and Hybpiper was able to ran around 15 SRA samples before it starts to pop up the error message ( not finding Biopython 1.8). So I believe installation was success in the first place as it worked for a week. 

According to your suggestion, here is the output of `cat $(which hybpiper)`
```
#!/bin/sh
'''exec' /home/fishball/miniconda3/envs/hybpiper/bin/python "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys
from hybpiper.assemble import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```
and I export this path `/home/fishball/miniconda3/envs/hybpiper/bin/ ` , the error still remains. 


About BioPython 1.79 , it may come with other program that I installed before. And I found following paths when I locate biopython. So does it means Biopython 1.8 is installed ? 


```
/home/fishball/miniconda3/envs/hybpiper/lib/python3.9/site-packages/biopython-1.80.dev0.dist-info
/home/fishball/miniconda3/envs/hybpiper/lib/python3.9/site-packages/biopython-1.80.dev0.dist-info/INSTALLER
/home/fishball/miniconda3/envs/hybpiper/lib/python3.9/site-packages/biopython-1.80.dev0.dist-info/LICENSE
/home/fishball/miniconda3/envs/hybpiper/lib/python3.9/site-packages/biopython-1.80.dev0.dist-info/LICENSE.rst
/home/fishball/miniconda3/envs/hybpiper/lib/python3.9/site-packages/biopython-1.80.dev0.dist-info/METADATA
/home/fishball/miniconda3/envs/hybpiper/lib/python3.9/site-packages/biopython-1.80.dev0.dist-info/RECORD
/home/fishball/miniconda3/envs/hybpiper/lib/python3.9/site-packages/biopython-1.80.dev0.dist-info/REQUESTED
/home/fishball/miniconda3/envs/hybpiper/lib/python3.9/site-packages/biopython-1.80.dev0.dist-info/WHEEL
/home/fishball/miniconda3/envs/hybpiper/lib/python3.9/site-packages/biopython-1.80.dev0.dist-info/direct_url.json
/home/fishball/miniconda3/envs/hybpiper/lib/python3.9/site-packages/biopython-1.80.dev0.dist-info/top_level.txt
```



I try to install Biopython 1.80 manually, but I can't find the source code on the website provided. Could you please provide other link direct to the code ? Sorry for the trouble.

Thank you very much for your help !

Alex

**Comment by chrisjackson-pellicle** [comment]
Hi Alex,

If I've understood you correctly, you:

1) Installed HybPiper using conda.
2) Ran HybPiper on some samples, and it ran successfully to completion.
3) Installed another program within the HybPiper conda environment, and this program also installed Biopython version 1.79.
4) You now get the Biopython version error when you run HybPiper.

If this is correct, then I think your best option is to remove the existing Hybpiper conda environment and re-create it, i.e.

`conda env remove --name hybpiper`
`conda create --name hybpiper`
`conda activate hybpiper`
`conda install -c chrisjackson-pellicle hybpiper`

This should return you to your previous, working, HybPiper conda environment.

In general, it's a good idea to keep your conda environments as small and simple as possible - that is, don't install too many tools within one environment. For HybPiper, it's best not to install any additional tools within the environment. This is particularly important when it comes to HybPiper's dependency on Biopython version 1.80. As described in the HybPiper documentation, Biopython version 1.80 does not have a release yet, and is not available as a conda package. When you install HybPiper via conda, Biopython version 1.80 is bundled with it, but this Biopython installation is not 'visible' to the conda package manager, and this can cause issues if you install other versions.

**Comment by chrisjackson-pellicle** [comment]
Hi Alex,

Great that you can get HybPiper working again, but I agree it's not the ideal solution!

I'm still not clear on what's happening on your system. As seen in the output of your `cat $(which hybpiper)` command, you're running HybPiper using the Python at `/home/fishball/miniconda3/envs/hybpiper/bin/python`. This Python installation should only be accessing the Biopython modules available in `/home/fishball/miniconda3/envs/hybpiper/lib/python3.9/site-packages/Bio`. 

If it can access a Biopython 1.79 installation that is installed somewhere *outside* your conda `hybpiper` environment,  it suggests that you have a parent directory of the Biopython 1.79 `Bio` folder in your `sys.path`, and that this occurs ahead of `/home/fishball/miniconda3/envs/hybpiper/lib/python3.9/site-packages/Bio`.

If you'd like to troubleshoot this further, can you re-create the problematic scenario, and post the output of the following commands from within your `hybpiper` conda environment?

1) `/home/fishball/miniconda3/envs/hybpiper/bin/python -c "import sys; print(sys.path)"` 

2) `echo $PYTHONPATH`


As an example, on my system the  command `/Users/chrisjackson/miniconda3/envs/hybpiper/bin/python -c "import sys; print(sys.path)"` returns:

```
['', '/Users/chrisjackson/miniconda3/envs/hybpiper/lib/python39.zip', '/Users/chrisjackson/miniconda3/envs/hybpiper/lib/python3.9', '/Users/chrisjackson/miniconda3/envs/hybpiper/lib/python3.9/lib-dynload', '/Users/chrisjackson/miniconda3/envs/hybpiper/lib/python3.9/site-packages']
```

...and the output of `echo $PYTHONPATH` is empty (i.e. the variable is unset).

Cheers,

Chris

**Comment by chrisjackson-pellicle** [comment]
Hi Alex,

I'll close this issue now due to lack of response, but feel free to re-open it if you'd like to troubleshoot further!
