### ISSUE TITLE
Error running the the dataset (HybPiper2 in macOS Monterey 12.4, chip M1)

### ISSUE THREAD

**Issue by DoveOfGlass** [mossmatters/HybPiper#84]
Hello, 

First, thank you for creating this great pipeline!

I am writing because I have encountered an error when I try to run the test_dataset in Hybpiper 2 and I don’t know how to fix it.

I have downloaded everything as is stated in the tutorial (using Conda), and when I check the dependencies all look fine. However, when I run " ./run_hybpiper_test_dataset.sh” or "hybpiper assemble -t_dna test_targets.fasta -r NZ281_R*_test.fastq --prefix NZ281 --bwa” I receive the following error (after running for a while):

[WARNING]: One or more genes had an error with SPAdes assembly. This may be due to low coverage.
[WARNING]: Total number of genes with failed SPAdes re-runs: 13. Gene names can be found in the sample log file.
[INFO]:    Finished re-running SPAdes assemblies for genes with unsuccessful initial assemblies!
ERROR: No genes had assembled contigs! Exiting!

I include a .txt with all the text from my terminal for a little bit more of context (including the list of all the dependencies installed) :).

Just in case it helps: my computer is a Mac mini with a M1 processor and MacOS Monterey 12.4. Also, some things that I have tried to solve it:

- Install HybPiper 1.3: the same error happens.
- Change the dependencies by hand to match the ones listed at: https://github.com/mossmatters/HybPiper/wiki/Installation. The error keeps happening.

More info: The command/script to do the sequences length test and to retrieve the sequences work (I did the assembling with another computer), but the intron assembly did not.

I am not sure if it is a problem with my installation, operative system or processor. Is there anything that I can try to fix it?

Thank you in advance for your help :)!!

[HybPiper2_Instalation-MacOSMonterreyM1_Error-TestDataset_NoContig.txt](https://github.com/mossmatters/HybPiper/files/8966935/HybPiper2_Instalation-MacOSMonterreyM1_Error-TestDataset_NoContig.txt)

**Comment by chrisjackson-pellicle** [comment]
Hi @DoveOfGlass,

It looks like there's an issue with the SPAdes assembler on your machine. I don't have a machine with an M1 chip or macOS Monterey to test with, but I wonder whether you've run in to this SPAdes issue: https://github.com/ablab/spades/issues/839

To check this, can you:

- Upload the sample log file within one of your sample directories (e.g. `EG30_hybpiper_assemble_<date-time>.log`
- Upload the `spades.log` file in the sample directory?

As you'll see in the issue thread linked above, if you are running in to the same problem then it's apparently been resolved in SPAdes version 3.15.4. Unfortunately, the highest version currently available as a conda package for macOS is 3.15.2 (https://anaconda.org/bioconda/spades), which is what (should) be installed when you install HybPiper via conda.

One of the workarounds suggested in the issue thread is to use the flag `--memory 1024` with the `spades.py` command. To test whether this solves your problem, can you please:

- Check whether you can successfully run a `spades.py` assembly from the command line within your `hybpiper` environment, using the following two commands:
    - spades.py --test
    - spades.py --test --memory 1024 

If the second command works for you, I can push an update of HybPiper that uses `--memory 1024` when calling `spades.py`.

Alternatively, as a temporary workaround you could download the Darwin release of SPAdes 3.15.4 from here https://github.com/ablab/spades/releases/tag/v3.15.4, unzip it, and add the SPAdes `bin` directory to the front of your $PATH, e.g. `export PATH="/Users/chrisjackson/Desktop/Programs/SPAdes-3.15.4-Darwin/bin/:$PATH"` (of course, change the path  to the `bin` directory to point to the location on your machine, and make sure to run the export command from within your conda `hybpiper` environment. You'll need to run the export each time you activate the environment).

Of course, all the suggestions above assume you're dealing with the same issue mentioned in the issue thread! Let me know how you go, and we can troubleshoot further if none of the above works.

Cheers,

Chris

**Comment by chrisjackson-pellicle** [comment]
Hi Paloma,

Excellent, glad it's working! I've just pushed an update (`hybpiper -v` should return `hybpiper 2.0.1rc build 11` once you've updated) which runs adds the flag `--memory 1024` to the `spades.py` command. Can you check to see of this fixes the problem, as we expect?

Cheers,

Chris

**Comment by DoveOfGlass** [comment]
Hi Chris!

I just have updated hybpiper to hybpiper 2.0.1rc build 11 and repeated the test dataset successfully. Everything works wonderfully! :)) I can confirm that the update fixes the problem that I was having.

Thank you very very much for all the help!

All the best,
Paloma
