### ISSUE TITLE
 Running exonerate_hits for 387 genes....  One of them reported an error

### ISSUE THREAD

**Issue by wudongyi534** [mossmatters/HybPiper#87]
I am running hybpiper assemble using a reference that has 400 genes,  I'm testing the pipeline on one sample before going for more. I got the following error, the log file no longer adds information but the program keeps running:

```
[INFO]:    Finished running Exonerate for gene gene0311, 295/387
[ERROR]:   Running bbmap.sh during the stitched-contig chimera test failed for gene
           gene0213. No stitched-contig chimera test will be performed. See the *.log file
           in the sample directory for error details.
[ERROR]:   Running bbmap.sh during the stitched-contig chimera test failed for gene
           gene0209. No stitched-contig chimera test will be performed. See the *.log file
           in the sample directory for error details.
[INFO]:    Finished running Exonerate for gene gene0074, 296/387
```
However, when I reduced the number of reference genes to 100, it worked

**Comment by wudongyi534** [comment]
The log file ends up with this error: 
```
[INFO]:    Finished running Exonerate for gene gene0765, 327/835
[INFO]:    Finished running Exonerate for gene gene0491, 328/835
[INFO]:    Finished running Exonerate for gene gene0325, 329/835For gene gene0434 exonerate() raised: Abnormal termination
```

**Comment by chrisjackson-pellicle** [comment]
Hi @wudongyi534,

The log file that should contain diagnostic information will be in your sample folder, with a name like `<prefix>_hybpiper_assemble_<date_time>.log`. Can you upload this file, please?

Cheers,

Chris

**Comment by wudongyi534** [comment]
[22R00099CS_hybpiper_assemble_2022-07-18-11_07_36.log](https://github.com/mossmatters/HybPiper/files/9129319/22R00099CS_hybpiper_assemble_2022-07-18-11_07_36.log)
[nohup.log](https://github.com/mossmatters/HybPiper/files/9129329/nohup.log)
 
These are two log files

**Comment by chrisjackson-pellicle** [comment]
Hi @wudongyi534,

Based on your log files, there are a few issues to address. These are:

1) The error `RuntimeError: can't start new thread`, produced by the Python `threading.py` module.
2) The `[ERROR]:   Running bbmap.sh during the stitched-contig chimera test failed...` errors.
3) The final `For gene gene0154 exonerate() raised: Abnormal termination` error.

I think solving error # 1 first would be best, as it's likely at least part of the problem with errors 2 and 3.

Your log file contains the entry:

> Number of cpus/threads not specified, using all available (112)

... and HybPiper appears to be having an issue when starting a new thread. Are you or other people using other programs at the same time that use a lot of threads? If so, can you try running HybPiper with a reduced number of threads by using the `--cpu` parameter with the command `hybpiper assemble`?

Cheers,

Chris

P.S. in your first post you stated that your reference (I assume you mean target file?) contains 400 genes, but your log file states: 

> The target file contains at least one sequence for 1044 unique genes. 

I'm not sure what's going on there, but wanted to make sure you noticed the discrepancy.

**Comment by wudongyi534** [comment]
Hi
 The sample was successfully tested with HybPiper. Thank you very much for your help




All the best










At 2022-07-18 12:50:05, "Chris Jackson" ***@***.***> wrote:

Hi @wudongyi534,

Based on your log files, there are a few issues to address. These are:

The error RuntimeError: can't start new thread, produced by the Python threading.py module.
The [ERROR]: Running bbmap.sh during the stitched-contig chimera test failed... errors.
The final For gene gene0154 exonerate() raised: Abnormal termination error.

I think solving error # 1 first would be best, as it's likely at least part of the problem with errors 2 and 3.

Your log file contains the entry:

Number of cpus/threads not specified, using all available (112)

... and HybPiper appears to be having an issue when starting a new thread. Are you or other people using other programs at the same time that use a lot of threads? If so, can you try running HybPiper with a reduced number of threads by using the --cpu parameter with the command hybpiper assemble?

Cheers,

Chris

P.S. in your first post you stated that your reference (I assume you mean target file?) contains 400 genes, but your log file states:

The target file contains at least one sequence for 1044 unique genes.

I'm not sure what's going on there, but wanted to make sure you noticed the discrepancy.
