### ISSUE TITLE
Subprocess module fails when default shell is dash

### ISSUE THREAD

**Issue by mossmatters** [mossmatters/HybPiper#89]
The issue I mentioned the other day with the `time` module wasn't as innocent as I thought. When running `hybpiper assemble` on the Cyverse nodes, the `subprocess.run()` command fails:

```
BWA mapping FAILED. Output is: Command 'time bwa mem -t 24 mega353.fasta /home/jovyan/work/ERR5034798_1.fastq.gz /home/jovyan/work/ERR5034798_2.fastq.gz  | samtools view -h -b -S - >  ERR5034798.bam' returned non-zero exit status 1.
BWA mapping stdout is: 
BWA mapping stderr is: /bin/sh: 1: time: not found
[main_samview] fail to read the header from "-".
```

I've discovered it is because `subprocess` defaults to `/bin/sh` and on these machines, `/bin/sh` is symlinked to `dash` rather than `bash` or `zsh`.

The executable can be set within `subprocess`. When I run within ipython, this works:

```python
result = subprocess.run(full_command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
   ...:                                 universal_newlines=True, check=True,executable="/bin/bash")
```

This fails:

```python
result = subprocess.run(full_command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
   ...:                                 universal_newlines=True, check=True,executable="/bin/dash")
```

Should we force `subprocess` to use `bash`? I have never heard of `dash` before getting this error, so I don't know how widespread of an issue this will be.

**Comment by mossmatters** [comment]
Short update - other machines I've installed HybPiper on also have `sh` symlinked to `dash` but HybPiper runs fine. The `time` module is installed on the Cyverse nodes, so I'm not sure what's going on here. Any ideas?

**Comment by mossmatters** [comment]
`mamba install time` did fix the issue - should we add it to the conda recipe? Will that cause any problems?

**Comment by chrisjackson-pellicle** [comment]
Shouldn't be a problem to include `time` as a dependency - it'll just install GNU `time` and use that in place of any shell builtin `time`. But, what do you think about simply removing the call to `time` in the various commands? It's a carryover from HybPiper 1.3 - do you think this is still useful information to capture? The log file now captures the time every time it's written to, so it largely covers this base, I reckon?

**Comment by chrisjackson-pellicle** [comment]
`time` has been removed from all BWA and blastx command strings, and is no longer used by HybPiper
