### ISSUE TITLE
conda install with an bug report

### ISSUE THREAD

**Issue by Fzhao89** [mossmatters/HybPiper#90]
I have a bug to report, When I install the hybpiper by conda. an error have been meet, the incomplete pakages with the Exonerate 2.40 have been report and the hybpiper faile to install.

**Comment by chrisjackson-pellicle** [comment]
Hi @Fzhao89,

I don't quite follow what the exact issue is. Can you attach the output of any errors you received?

Cheers,

Chris

**Comment by pur80a** [comment]
Oracle linux: 8.6 
Linux: 4.18.0 
miniconda: 4.13.0 
```
conda create -p $(pwd)/2022-09-14-hybpiper -c chrisjackson-pellicle hybpiper=2.0.1
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError:

```
I don't get any more info and using the `-v` flag doesn't seem to give more insight ... 
I'd be happy to provide more info if needed. 

Best regards

**Comment by chrisjackson-pellicle** [comment]
Hi @pur80a  - sorry for the delay, I just got back from leave.

Have you added the correct conda channels, as described [here][1]? I've seen this error before when the channels haven't been added. 

Cheers,

Chris

[1]: https://github.com/mossmatters/HybPiper/wiki/Installation#hybpiper-installation

**Comment by pur80a** [comment]
Hi @chrisjackson-pellicle thanks for the reply. 
In the meantime I've  succeeded by installing from source: 
```
URL="https://anaconda.org/chrisjackson-pellicle/hybpiper/2.0.1rc/download/linux-64/hybpiper-2.0.1rc-h9bf148f_13.tar.bz2
mkdir ${TARGETDIR}
pushd ${TARGETDIR}
        wget $URL
        tar xf hybpiper-2.0.1rc-h9bf148f_13.tar.bz2
        rm hybpiper-2.0.1rc-h9bf148f_13.tar.bz2
        sed -i "s#/home.*python#python3#" bin/hybpiper
popd
```
I think that you are right, though and I just forgot to include the channels. I guess my command should have looked like this:
``` 
conda create -p $(pwd)/2022-09-14-hybpiper -c chrisjackson-pellicle -c bioconda -c conda-forge hybpiper=2.0.1
```
