### ISSUE TITLE
ValueError: No records found in handle; stats and paralog_retriever

### ISSUE THREAD

**Issue by SethMusker** [mossmatters/HybPiper#97]
See the attached log files. I suppose this has to do with some sequences not being recovered in some samples? But I can't tell which they might be based on the log files.

Code for `stats`:
```
hybpiper stats --targetfile_dna ${TARGETS} \
    --seq_lengths_filename ../stats/hybpiper_gene_lengths \
    --stats_filename ../stats/hybpiper_gene_stats \
    gene ${SAMPLES}
```
[725033_stats.err.txt](https://github.com/mossmatters/HybPiper/files/9505841/725033_stats.err.txt)

Code for `paralog_retriever`:
```
hybpiper paralog_retriever --targetfile_dna ${TARGETS} \
    --heatmap_filetype pdf \
    ${SAMPLES}
```
[724924_paralogs.err.txt](https://github.com/mossmatters/HybPiper/files/9505842/724924_paralogs.err.txt)

The targets and samples variables point to the ones passed to `assemble`.

Oddly, `stats` works for supercontigs. I think this might be because some sequences had introns but not exons assembled, which sounds weird but actually makes sense because we used a somewhat unorthodox target capture design approach for some targets.

What information do these modules take from the target fasta provided? Some of my targets have one source while others have two -- will that make a difference?

Cheers,
Seth

**Comment by chrisjackson-pellicle** [comment]
Hi Seth,

First, a disclaimer that'll apply to your other issues too: I'm on parental leave until mid-November, so I'm functioning on very little sleep and I have very limited time to look at issues. It also means that some of my responses might be gibberish :) With that said, I'll work through them as/when I get a chance!

Both `stats` and `paralog_retriever` check for the existence of the  `*.FNA` and\/or `*.FAA` files\\paths before trying to read a sequence from the files (I'll change this to also check for non-empty files in a future release, and catch any errors). So, the error you're seeing suggests that you have nucleotide or protein (`*.FNA` or `*.FAA`) files that exist but are empty, which, unless there's a bug I've missed, shouldn't be happening. These files should only be created if there's a corresponding sequence to be written. 

To help troubleshoot this, can you check for the presence of such empty files? If you're in the directory that contains your sample folders, you could use a command such as:

```
find  */*/*/sequences -name "*.FNA" -exec  ls -lhS {} \+
```

...which should list the smallest *.FNA file size last. Are there empty files present?

Regarding your question about the target fasta file: `paralog_retriever` just uses it to parse a list of gene names, whereas`stats` parses the reference sequence lengths in the target file. For the latter, if more that one representative reference sequence is present for a given gene, the mean length is used (so, no problem to have different numbers of refs for different genes).

Cheers,

Chris

**Comment by SethMusker** [comment]
Hi Chris,

Thanks for your time, especially given the circumstances! Much appreciated.

Thanks for the command. Indeed, the gene that `paralog_retriever` failed at had one sample whose FNA was empty. The exonerate step timed out, but other genes did too and they have no FNA so it worked normally for those. No apparent errors thrown in the log file.

Still waiting for the rest of the genes' file sizes to get reported, after which I'll just delete any empty FNAs before rerunning, and report back.

S

p.s. no gibberish detected ;)

**Comment by chrisjackson-pellicle** [comment]
Ah, I didn't think of the Exonerate timeout issue! Can you let me know if more than one `*.FNA` is empty? I wonder if, by chance, the Exonerate module got cancelled just after the `*.FNA` file was created, but before data was written to it. Unlikely, but possible, I guess. 

To help diagnose the problematic files in future, I've just pushed an update (and updated the conda packages) that includes a check for fasta files that exist but are empty when running `stats` and `paralog_retriever`, as well as `retrieve sequences`. It'll now print a warning listing the problematic file paths, but should otherwise continue.

If you've successfully installed the latest version, running `hybpiper -v` should return `hybpiper 2.0.1rc build 13`. Also see the `change_log.md` file for a few other changes.

Cheers,

Chris

**Comment by chrisjackson-pellicle** [comment]
Congratulations on finishing your PhD!

No problem - I'll close this issue for now, but let me know if it comes up again.

Cheers,

Chris
