### ISSUE TITLE
verions 2.0.1 tag/release

### ISSUE THREAD

**Issue by pur80a** [mossmatters/HybPiper#99]
Dear developers, 

please make a tag or even better a release for the newest version. 
Otherwise I just have to pull whatever the latest commit was in order to install. 

Thanks

**Comment by mossmatters** [comment]
@chrisjackson-pellicle are you ok with tagging the most recent commit as "2.0.1 release candidate"?

**Comment by chrisjackson-pellicle** [comment]
@mossmatters can't see why not!

**Comment by mossmatters** [comment]
We now have a release tagged 2.0.2, hope this helps!
